"""Manual decisions for the phase-3 rename plan, from reviewing rename-plan.csv by eye (6 Oct 2026).
OVERRIDES: key = path relative to the root folder (or bare file name) -> clean stem (extension added) or "SKIP".
WORD_FIX: whole-word fixes (lower-case word -> correct word).
PHRASE_FIX: whole-name spelling fixes (lower-case clean name, without version/markers -> correct name).
JUNK_NAMES: words that are not a name on their own (a file whose clean name is only these is left as is)."""
OVERRIDES = {
    "LOTR - LEGOLAS.jpg": "Legolas (Lord of the Rings)",
    "Spock - Recent film - Quinto.jpg": "Spock (Zachary Quinto)",
    "Mamma Mia - Julie Walters.jpg": "Julie Walters",
    "Mamma Mia-Julie Walters__15459.jpg": "Julie Walters",
}
WORD_FIX = {
    "oporter": "O'Porter", "omeara": "O'Meara", "dell'olio": "Dell'Olio", "arsne": "Arsene", "jmaes": "James",
    "debbyryan": "Debby Ryan", "danniel": "Daniel", "nedal": "Nadal", "buscell": "Bussell", "huges": "Hughes",
    "hiddlestone": "Hiddleston", "chalemet": "Chalamet", "cribbinis": "Cribbins", "boradbent": "Broadbent",
    "piorot": "Poirot", "hasslehoff": "Hasselhoff", "donnolly": "Donnelly", "mcpartlain": "McPartlin",
    "stricktly": "Strictly", "gerogina": "Georgina", "jiigsaw": "Jigsaw", "loona": "Luna",
}
PHRASE_FIX = {
    "kirsten wiig": "Kristen Wiig", "kit harrington": "Kit Harington", "brit ekland": "Britt Ekland",
    "mathew pinsent": "Matthew Pinsent", "stephanie powers": "Stefanie Powers", "jessica beil": "Jessica Biel",
    "blanch hunt": "Blanche Hunt", "martin mcguiness": "Martin McGuinness", "todd stashwic": "Todd Stashwick",
    "mo farrah": "Mo Farah", "marie le pen": "Marine Le Pen", "rafa nadal": "Rafa Nadal", "ian mckellen": "Ian McKellen",
    "moulin jim broadbent": "Jim Broadbent", "hercule poirot": "Hercule Poirot", "david hasselhoff": "David Hasselhoff",
    "arthur ashe": "Arthur Ashe", "arther ashe": "Arthur Ashe", "lamar odon": "Lamar Odom", "danill kvyat": "Daniil Kvyat",
    "jaylon palmer": "Jolyon Palmer", "brock lesner": "Brock Lesnar", "ben ainsley": "Ben Ainslie",
    "dwayne wade": "Dwyane Wade", "bob bryans": "Bob Bryan", "sheryll cole": "Cheryl Cole", "janette manarara": "Janette Manrara",
    "giovani pernice": "Giovanni Pernice", "trent whiddon": "Trent Whiddon", "shridan smith": "Sheridan Smith",
    "decland donnelly": "Declan Donnelly", "ferne cotton": "Fearne Cotton", "aaron chalmer": "Aaron Chalmers",
}
JUNK_NAMES = {"l", "intro", "shutterstock", "untitled", "image", "img", "maxresdefault", "charwwacters", "landscape",
              "olympic", "masks", "mask", "dsc", "photo", "screenshot", "screen", "shot", "unnamed", "download",
              "default", "large", "small", "thumb", "thumbnail", "original", "lead", "jpg", "e", "s", "full", "x",
              "p", "aa", "b1t", "h9", "the", "a", "-", "and", "of", "wp", "ink", "grude", "cc", "r", "v1", "mv5b"}

# second review pass (6 Oct): spelling, glued names, actor+character names -> actor, leftover descriptors
PHRASE_FIX.update({k.lower(): v for k, v in {
    "Amy Whinehouse": "Amy Winehouse", "Abhishek Bachan": "Abhishek Bachchan", "Ahley Roberts": "Ashley Roberts",
    "Alan Partidge": "Alan Partridge", "Andre Aggasi 80's": "Andre Agassi 80's", "Andre Reiu": "Andre Rieu",
    "Andrew Ridgely": "Andrew Ridgeley", "Ann Widecombe": "Ann Widdecombe", "Arnold Schwartzenegger": "Arnold Schwarzenegger",
    "Ashton Kutchar": "Ashton Kutcher", "Bacaray Sagna": "Bacary Sagna", "Balldrick": "Baldrick", "Barbera Windsor": "Barbara Windsor",
    "Bill Odie": "Bill Oddie", "Billy Bob Thorton": "Billy Bob Thornton", "Bradd Pitt": "Brad Pitt", "Bruce Springstein": "Bruce Springsteen",
    "Bruno Guimareas Blonde": "Bruno Guimaraes Blonde", "Bruno Guimareas Dark Hair": "Bruno Guimaraes Dark Hair",
    "Brian O'Driscol": "Brian O'Driscoll", "Brendan Rogers": "Brendan Rodgers", "Brendan Rodgers Celtic": "Brendan Rodgers",
    "Cara Delevigne": "Cara Delevingne", "Catherine Tyledesley": "Catherine Tyldesley", "Chad Michael Murry": "Chad Michael Murray",
    "Christ Froome": "Chris Froome", "Christain Horner": "Christian Horner", "Christian Erikson": "Christian Eriksen",
    "Courtney Cox": "Courteney Cox", "Claudia Winkelman": "Claudia Winkleman", "Connor McGreggor": "Conor McGregor",
    "Connor McGregor": "Conor McGregor", "Danny Wellbeck": "Danny Welbeck", "Danny Odonoghue": "Danny O'Donoghue",
    "Daniel O'Donnel": "Daniel O'Donnell", "Daniel Ricardo": "Daniel Ricciardo", "Darlek Party": "Dalek Party",
    "David Coultard": "David Coulthard", "David Willets": "David Willetts", "Des O'Conner": "Des O'Connor",
    "Dennis Quiad": "Dennis Quaid", "Dennis Irwin": "Denis Irwin", "Domonic Cooper": "Dominic Cooper", "Dwayne Chambers": "Dwain Chambers",
    "Ed Helmsl": "Ed Helms", "Elle Macphereson": "Elle Macpherson", "Emanuel Macron": "Emmanuel Macron", "Emile Heskeyy": "Emile Heskey",
    "Eric Cantonna": "Eric Cantona", "Eric Morcambe": "Eric Morecambe", "Eric Morcambe Old": "Eric Morecambe Old", "Erol Flynn": "Errol Flynn",
    "Farrah Fawcet": "Farrah Fawcett", "Forrest Whittaker": "Forest Whitaker", "Frankie Detori": "Frankie Dettori",
    "Freddy Flintoft Cartoon": "Freddie Flintoff Cartoon", "Frank SinatrA": "Frank Sinatra", "Gary Nevvile": "Gary Neville",
    "Geaorge Ford": "George Ford", "Geaorge Harrison": "George Harrison", "Genmma Atkinson": "Gemma Atkinson", "Geoff Hurst Youg": "Geoff Hurst Young",
    "Duncan Banatyne": "Duncan Bannatyne", "Fiscishella": "Giancarlo Fisichella", "Felipao Scholari": "Felipe Scolari",
    "Mirander Hart": "Miranda Hart", "Heather Small Mirander": "Heather Small", "Darceybussell": "Darcey Bussell",
    "Dell Boy": "Del Boy", "DellTrotter": "Del Trotter", "Dell Trotter": "Del Trotter", "Frankturner": "Frank Turner",
    "Boygeorge": "Boy George", "Boy George Dec": "Boy George", "Janeseymour": "Jane Seymour", "Kellyosbourne": "Kelly Osbourne",
    "Kelly Osbourne Darkjpg": "Kelly Osbourne Dark", "Lionelmessi": "Lionel Messi", "LadygagaBIG": "Lady Gaga", "LuluPOOR": "Lulu",
    "Lukeshaw": "Luke Shaw", "Loveisland Adam": "Adam (Love Island)", "Macenroe": "John McEnroe", "Mariah.carey": "Mariah Carey",
    "Selenagomez": "Selena Gomez", "Sammydavisjr": "Sammy Davis Jr", "Rogermoore": "Roger Moore", "SeanOBrien": "Sean O'Brien",
    "TristanMacManus": "Tristan MacManus", "This Tom JonesTom Jones": "Tom Jones", "JimmyFallon": "Jimmy Fallon",
    "JohnHannah": "John Hannah", "JudyFinnegan": "Judy Finnegan", "Bean": "Mr Bean", "BeanMask": "Mr Bean",
    "Adrian Brodyjb": "Adrien Brody", "Adrian Brody": "Adrien Brody", "AustinPowers": "Austin Powers", "StarWars": "Star Wars",
    "Gordon Ramsey": "Gordon Ramsay", "Harry Rednapp": "Harry Redknapp", "Henrik Mkhitaryan": "Henrikh Mkhitaryan",
    "Hideki Matsuyam": "Hideki Matsuyama", "Hilary Clinton": "Hillary Clinton", "Hugo LLoris": "Hugo Lloris",
    "Incredilbe Hulk": "Incredible Hulk", "Indianna Jones Big": "Indiana Jones", "Jamie Brysonnn": "Jamie Bryson",
    "Jane Horricks": "Jane Horrocks", "Jasper Carrot": "Jasper Carrott", "Jenifer Saunders": "Jennifer Saunders",
    "Jennyfar Lopz": "Jennifer Lopez", "Jensen Button": "Jenson Button", "Jermain Defoe": "Jermain Defoe", "Jimmy Osmand": "Jimmy Osmond",
    "Joan Simms": "Joan Sims", "Johan Blake": "Yohan Blake", "John Malcovich": "John Malkovich", "John McClain": "John McClane",
    "Jonny Depp": "Johnny Depp", "Jordan Speith": "Jordan Spieth", "Jordon Speith": "Jordan Spieth", "Jos Butler": "Jos Buttler",
    "Julian Clarey": "Julian Clary", "Julian Cleary": "Julian Clary", "Jurgen Klinsman": "Jurgen Klinsmann", "Justin Beiber": "Justin Bieber",
    "Young Justin Beiber": "Justin Bieber Young", "Kate Winslett": "Kate Winslet", "Kendell Jenner": "Kendall Jenner",
    "Kevin McLoud": "Kevin McCloud", "Kevin Pieterson": "Kevin Pietersen", "Kevinh Hart": "Kevin Hart", "Kiera Walsh": "Keira Walsh",
    "Kim John Un": "Kim Jong Un", "Kim Jong": "Kim Jong Un", "Lan Shearer": "Alan Shearer", "Lauren Cohen": "Lauren Cohan",
    "Liza Minelli": "Liza Minnelli", "Loraine Kelly": "Lorraine Kelly", "Lorriane Kelly": "Lorraine Kelly", "Leonardo di Caprio": "Leonardo DiCaprio",
    "Mario Ballotelli": "Mario Balotelli", "Marouanne Fellaini": "Marouane Fellaini", "Mourouane Fellani": "Marouane Fellaini",
    "Mark Ruffallo": "Mark Ruffalo", "Marylin Monroe": "Marilyn Monroe", "Matthew McMonaughey": "Matthew McConaughey",
    "Megan Markel": "Meghan Markle", "Megan Markle M": "Meghan Markle", "Mesult Ozil": "Mesut Ozil", "Mervin King": "Mervyn King",
    "Micheal Kessler": "Michael Kessler", "Michelle ObamaMINT": "Michelle Obama", "Miley Cyris": "Miley Cyrus", "Miriah Carey": "Mariah Carey",
    "Mick Huknall Shit": "Mick Hucknall", "Michael Macyntyre": "Michael McIntyre", "Nemaja Vidic": "Nemanja Vidic",
    "Nial Horran Smirk": "Niall Horan Smirk", "Nico HUlkenberg Cap": "Nico Hulkenberg Cap", "Nikki Minaje": "Nicki Minaj",
    "Nikki Minaje Proof": "Nicki Minaj", "Novak Djokavic": "Novak Djokovic", "Olivia Newtonjohn": "Olivia Newton John",
    "Paul Gascgoine": "Paul Gascoigne", "Paul McArtney Grey": "Paul McCartney Grey", "Paul Merson2": "Paul Merson",
    "Penelope Kieth": "Penelope Keith", "Peter Otoole": "Peter O'Toole", "Piers Brosnan": "Pierce Brosnan", "Pinoccio": "Pinocchio",
    "Pollyann Wwoodward": "Pollyanna Woodward", "Pricess Sophie of Wessex": "Princess Sophie of Wessex", "Princess Eugene": "Princess Eugenie",
    "Racvhel Miner": "Rachel Miner", "Rob Kardashain": "Rob Kardashian", "Robert Downy JR": "Robert Downey Jr", "Robert Downey JR": "Robert Downey Jr",
    "Roberto Firminho": "Roberto Firmino", "Roger Federa": "Roger Federer", "Ronnie Mithcell Samantha Womack": "Samantha Womack",
    "Rosie Hunington Whiteley Oscars": "Rosie Huntington Whiteley", "Rowan Atkin": "Rowan Atkinson", "Roy Hodgeson": "Roy Hodgson",
    "Russel Brand": "Russell Brand", "Russel Crowe": "Russell Crowe", "Sally Ann Mattews": "Sally Ann Matthews", "Salma Hyeck": "Salma Hayek",
    "Samanth Cameron": "Samantha Cameron", "Samual L Jackson": "Samuel L Jackson", "Sammy Davies Jnr": "Sammy Davis Jr", "Sammy Davis JR": "Sammy Davis Jr",
    "Scarlette Johanson": "Scarlett Johansson", "Seann Willia Scott": "Seann William Scott", "Sean William Scott (American Pie)": "Seann William Scott",
    "Sebastain Vettel": "Sebastian Vettel", "Sebastian Vettell": "Sebastian Vettel", "Sergeo Agureo": "Sergio Aguero", "Serina Wiegman": "Sarina Wiegman",
    "Shaquile Oneil": "Shaquille O'Neal", "Sheree Whilfield": "Sheree Whitfield", "Shon McGARTY": "Shona McGarty", "Simon Cowel": "Simon Cowell",
    "Sophie Ellis Bexter": "Sophie Ellis Bextor", "Stanley Tuccii": "Stanley Tucci", "Stalone": "Sylvester Stallone", "Steffi Graff": "Steffi Graf",
    "Steven Gerard": "Steven Gerrard", "Talyor Swift": "Taylor Swift", "Talyor Swift Bob": "Taylor Swift Bob", "Taylor+swift+new+mj": "Taylor Swift",
    "Tom Daly": "Tom Daley", "Tommy Le Jones": "Tommy Lee Jones", "Torvill And Deane": "Torvill and Dean", "Ulrika Johnson": "Ulrika Jonsson",
    "Ursula Anders": "Ursula Andress", "Vacky Pattinson Short Hair": "Vicky Pattison Short Hair", "Vannessa Feltz": "Vanessa Feltz",
    "Vigo Mortensen": "Viggo Mortensen", "Xi Jin Ping": "Xi Jinping", "Yoday": "Yoda", "Young Ewan McGreggor": "Ewan McGregor Young",
    "Young Mel Gibson": "Mel Gibson Young", "Zach Galifinakis": "Zach Galifianakis", "Bald Zach Galifinakis": "Zach Galifianakis Bald",
    "Zara Philips": "Zara Phillips", "Zoey Saldana": "Zoe Saldana", "Hema Malinis": "Hema Malini", "Arlene Philips": "Arlene Phillips",
    "Catherine Zeta Jones": "Catherine Zeta Jones", "Agnetha Faltskog": "Agnetha Faltskog", "Gease (Sandy2)": "Sandy (Grease) 2",
    "Danny Grease": "Danny (Grease)", "Phil Hangover": "Phil (The Hangover)", "Jedward Edward": "Edward (Jedward)", "Jedward John": "John (Jedward)",
    "Pepsi Wham": "Pepsi", "Shirlie Wham": "Shirlie", "Mike Sr3": "Mike (Love Island)", "Sr3 Dom": "Dom (Love Island)",
    "Ted Hankey The Count": "Ted Hankey", "Phil The Power Taylor": "Phil Taylor", "Chris Kamara a": "Chris Kamara",
    "Julia Gillard June a": "Julia Gillard", "Pele Footballer": "Pele", "Nelly Rapper": "Nelly", "Usher Music": "Usher",
    "Justin Bieber Fox": "Justin Bieber", "Steven Gerrard Fox": "Steven Gerrard", "Bono Fox": "Bono", "Gan Fox": "Megan Fox",
    "Xavi1 Barcelona": "Xavi", "Hello Kitty001": "Hello Kitty", "Michael Hassini.2": "Michael Hassini", "Rhona) (Emmerdale)": "Rhona (Emmerdale)",
    "Player Dan Cole": "Dan Cole", "Michael Smith Player": "Michael Smith", "O Denise Welch Facebook": "Denise Welch",
    "Simon Pegg Picture": "Simon Pegg", "Kate Bush Better": "Kate Bush", "Zac Efron Best": "Zac Efron", "Tin Tin Best": "Tin Tin",
    "Ozzy Osbourne Best": "Ozzy Osbourne", "Rosie Fortescue Best": "Rosie Fortescue", "Kim Cattrall Best": "Kim Cattrall",
    "Michael Holding Best": "Michael Holding", "Jurgen Klopp Best": "Jurgen Klopp", "Miranda Best": "Miranda Hart",
    "Mary Berry Bookl": "Mary Berry", "Will Simon Bird 2 Ok": "Simon Bird", "Pennywise It Converted": "Pennywise",
    "Kristen Stewart V2": "Kristen Stewart", "Owen Template": "Owen", "Zebra Template": "Zebra", "Netflix Maid Book T": "SKIPNAME",
    "Vikings Star Ludwig Relishes Unconventional Techie Role In": "Alexander Ludwig", "Spiral Sequel Jigsaw John Kramer": "Jigsaw",
    "Sulley and Mike Set Buy Disney Monsters University Star At Starstills": "Sulley and Mike",
    "Transparent Moomintroll Moomins Art Moomin White Food Cartoon Thumbnail": "Moomintroll",
    "Transparent White Animal Moomintroll Moomins Snufkin Moominmamma Moominpappa Bok Choy Miscellaneous White Mammal": "Moomin Family",
    "Tumblr Xkoqqmrm Meixo": "SKIPNAME", "Id81 24 Tom Segura": "Tom Segura", "2 Ehp Chp MacDowell": "Andie MacDowell",
    "Stormfront la Ai": "Stormfront", "Raquel Murillo Or Lisbon": "Lisbon (Money Heist)", "Raymond Ablack Ginny Georgia Maid": "Raymond Ablack",
    "Paola Nunez Height": "Paola Nunez", "Season (Money Heist)": "SKIPNAME", "The Victim S1": "SKIPNAME", "Mnpcawiinla": "SKIPNAME",
    "Maxresdefault6t": "SKIPNAME", "Photos": "SKIPNAME", "Mis": "SKIPNAME", "Life Lessons": "SKIPNAME", "Maid Unit": "SKIPNAME",
    "Kellyhoppen Address London": "Kelly Hoppen", "Skysports Oscar Piastri McLaren": "Oscar Piastri", "Romeo Beckham Burberry Garticle": "Romeo Beckham",
    "Richard Tice Reform UK": "Richard Tice", "Nigella Lawson Cookery Lady": "Nigella Lawson", "Playboy Hugh Hefner": "Hugh Hefner",
    "Morata Injury": "Alvaro Morata", "Owen Jadon Sancho": "Jadon Sancho", "Will Young August": "Will Young", "Orlando Bloom August": "Orlando Bloom",
    "Shikhar Dhawan Indian India": "Shikhar Dhawan", "Virat Kohli Indian India": "Virat Kohli", "Virat Kohli 2 Indian India": "Virat Kohli 2",
    "Rohit Sharma Indian India": "Rohit Sharma", "Rohit Sharma 2 Indian India": "Rohit Sharma 2", "Tony Pulis Welsh": "Tony Pulis",
    "Mark Warburton Glasgow": "Mark Warburton", "Hibernian Alan Stubbs": "Alan Stubbs", "Paolo Di Canio Sunderland": "Paolo Di Canio",
    "Ole Gunner Manchester United": "Ole Gunnar Solskjaer", "Fred Man Utd": "Fred", "Jose Mourinho Chelsea": "Jose Mourinho",
    "Steven Gerrard Rangers Boss": "Steven Gerrard", "Richard Ashcroft Oasis": "Richard Ashcroft", "Peter Salisbury the Verve": "Peter Salisbury",
    "Sharleen Spiteri Texas": "Sharleen Spiteri", "Mike Nolan Bucks Fizz": "Mike Nolan", "Tom Delonge Blink": "Tom DeLonge",
    "Travis Barker Blink": "Travis Barker", "Faye Tozier Steps": "Faye Tozer", "Claire Steps": "Claire Richards",
    "Danny Jones McFly": "Danny Jones", "Mel C Spice Girl": "Mel C", "Melanie C Spice Girl": "Melanie C",
    "Little Mix Leigh Anne Pinnock": "Leigh Anne Pinnock", "Little Mix Perrie Edwards": "Perrie Edwards", "Nsync1 Justin Timberlake": "Justin Timberlake",
    "Acdc Malcolm Young": "Malcolm Young", "Jungkook Jimin Jungshook": "SKIPNAME", "Rashford Foden Southgate Kane": "SKIPNAME",
    "Ford Kiernan and Greg Hemphill As Jack and Victor": "SKIPNAME", "Tommy Mallet and Georgia Kousoulou": "SKIPNAME",
    "Joel Dommett Im a": "Joel Dommett", "Samia Ghadie Maria Coranation Street": "Samia Ghadie", "Ryan Thomas Jason From": "Ryan Thomas",
    "Mel From": "Mel", "Lynn From Alan Partridge": "Lynn (Alan Partridge)", "Mel From Great British Smiley": "Mel (Bake Off) Smiley",
    "Tom Hardy Hunky Hardy Beard Style": "Tom Hardy Beard", "Bruce Lee Simple Short Hairstyle": "Bruce Lee Short Hair",
    "Rocky Balboa Best Young Sylvester Stallone": "Sylvester Stallone Young", "Kurt Cobain Rolling Stone Cover": "Kurt Cobain",
    "Jodie Whittaker The Thriteenth Doctor": "Jodie Whittaker", "Ncuti Gatwa The Fifteenth Doctor": "Ncuti Gatwa",
    "Finn Jones As Danny Rand In Marvels Iron Fist": "Finn Jones", "George Clarke Restoration TV Programs": "George Clarke",
    "Gunther Steiner At the Austrian Grand Prix": "Guenther Steiner", "David Seaman Tag Heuer": "David Seaman",
    "Lewis Hamilton Formula": "Lewis Hamilton", "Lewis Hamilton Malaysia": "Lewis Hamilton", "Charlie Keyy Sunny In Phillidelphia": "Charlie Kelly (It's Always Sunny in Philadelphia)",
    "Craig Gazey Greame Proctor": "Craig Gazey", "Steffan Rhodri Dave Coaches Gavin Stacey": "Steffan Rhodri", "Margaret John Doris Gavin Stacey": "Margaret John",
    "Kim and Agi": "SKIPNAME", "Pepsi and Shirlie": "SKIPNAME", "Wayne And Garth": "SKIPNAME", "Wayne and Garth": "SKIPNAME",
}.items()})
OVERRIDES.update({
    "Ford-Kiernan-and-Greg-Hemphill-as-Still-Games-Jack-and-Victor.jpg": "SKIP",
})
PHRASE_FIX.update({k.lower(): v for k, v in {
    "Pirates (Kiera)": "Keira Knightley", "Pirates": "Keira Knightley", "Robbie Jackson Dean Gaffney": "Dean Gaffney",
    "Jenna Ortega Wednesday Addams": "Jenna Ortega", "Jennifer Coolidge Stifflers Mom": "Jennifer Coolidge",
    "Headland Championship": "SKIPNAME",
}.items()})
OVERRIDES.update({"Pirates - Kiera.jpg": "Keira Knightley (Pirates of the Caribbean)"})
OVERRIDES.update({"hello_kitty001.png": "Hello Kitty", "Stewart- Lee.jpg": "Stewart Lee", "The swedish chef.jpg": "The Swedish Chef",
                  "Cricket Masks.jpg": "SKIP", "clarke2_1568138a.jpg": "Michael Clarke 2"})
OVERRIDES.update({"Pirates - Johnny Depp.jpg": "Johnny Depp (Pirates of the Caribbean)", "harry potter young.jpg": "Harry Potter Young",
                  "Mask of Loki-Jim Carrey-The Mask.jpg": "Jim Carrey (The Mask)", "Red Shawshank Morgan Freeman SJ2.jpg": "Morgan Freeman (Shawshank Redemption) SJ 2",
                  "GUS 2breaking bad.JPG": "Gus (Breaking Bad) 2", "Gease - Sandy2.jpg": "Sandy (Grease) 2", "ADRIAN BRODYJB.jpg": "Adrien Brody JB"})
OVERRIDES.update({"070 Shake.jpg": "070 Shake", "Little Mix - Jade Thirwall.jpg": "Jade Thirlwall",
                  "Little Mix - Jesy Nelson Mask - Copy - Copy - Copy - Copy.jpg": "Jesy Nelson", "Jo O'Meara _S Club 7.jpg": "Jo O'Meara",
                  "Nail - One Direction.JPG": "Niall Horan", "bdc617e4-df69-4eea-8264-778cc5c0713d.png": "SKIP"})
OVERRIDES.update({  # 6 Oct review before p1-02: "face" stripped inside Scarface, LOTR abbreviations, glued names
    "Scarface.jpg": "Scarface",
    "LOTR - Frodo.jpg": "Frodo (Lord of the Rings)",
    "LOTR - Galadrial.jpg": "Galadriel (Lord of the Rings)",
    "LOTR - Gandalf.jpg": "Gandalf (Lord of the Rings)",
    "LOTR - GIMLI.jpg": "Gimli (Lord of the Rings)",
    "LOTR - Gollum.jpg": "Gollum (Lord of the Rings)",
    "LOTR Gollum.jpg": "Gollum (Lord of the Rings)",
    "Aragorn-LOTR.jpg": "Aragorn (Lord of the Rings)",
    "boygeorge_portable.jpg": "Boy George",
    "Charlie - mk1.jpg": "Charlie (MK1)",
})
OVERRIDES.update({  # 6 Oct review (2): leftovers, acronyms, spellings
    "TOWIE's Georgia Kousoulou.jpg": "Georgia Kousoulou",
    "Michael Hassini.2 2020 Face.jpg": "Michael Hassini 2",
    "Donald+Trump m JB.jpg": "Donald Trump JB",
    "kelvin_fletcher_2003_10_28.jpg": "Kelvin Fletcher",
    "rob-kearney-60-752x501.jpg": "Rob Kearney",
    "Mike love island sr3 93 jpg 1497517560 2020 Face.jpg": "Mike (Love Island)",
    "harold_ramis_h_2016.jpg": "Harold Ramis",
    "James-Franco-58.jpg": "James Franco",
    "NKOTB1.JPG": "NKOTB", "JFK.JPG": "JFK", "lmfao.jpg": "LMFAO", "BFG.jpg": "BFG",
    "USA.jpg": "USA", "SZA 2023.jpg": "SZA", "c3po.jpg": "C3PO",
    "GHANDI.JPG": "Gandhi", "SWEEDEN.jpg": "Sweden",
})
WORD_FIX.update({"nkotb": "NKOTB", "lmfao": "LMFAO", "jfk": "JFK", "sza": "SZA", "bfg": "BFG", "c3po": "C3PO", "ksi": "KSI"})
OVERRIDES.update({  # 6 Oct review (3)
    "TOM JONES SJ2.jpg": "Tom Jones SJ 2",
    "corgi pup cut out.jpg": "Corgi Pup",
    "Camilla Coronation 2023-ROYALS.jpg": "Camilla",
    "THE QUEEN CROWN Coronation 2023-royals.jpg": "The Queen Crown",
    "RM Rap Master - BTS Korean Music Star K POP - Music Star Fancy Dress Cardboard celebrity face mask Fancy Dress Face Mask 2021.jpg": "RM (BTS)",
    "Stone Roses 3 Not Mint.JPG": "Stone Roses 3",
})
OVERRIDES.update({  # 6 Oct review (4)
    "Joachim Löw Mask JB .jpg": "Joachim Low JB",
    "Hibernian_FC_logo.svg.png": "SKIP",
    "victor Viktor Hovland - Golf.jpg": "Viktor Hovland",
    "Pieters_Thomas.jpg": "Thomas Pieters",
    "Snedeker_Brandt_10BAR2.jpg": "Brandt Snedeker",
    "Howard_Dwight.jpg": "Dwight Howard",
})
OVERRIDES.update({  # 6 Oct review (5)
    "BRITISH BAKE OFF NEW.jpg": "British Bake Off",
    "big best sex and city.jpg": "Mr Big (Sex and the City) 2",
    "Amanda Mealing (Connie) CASUALTY.jpg": "Amanda Mealing (Connie)",
    "Derek - Catherine Tate 1.jpg": "Derek (Catherine Tate)",
    "Derek - Catherine Tate 2.jpg": "Derek (Catherine Tate) 2",
    "David- Lost boys -Keifer Sutherland (larger).jpg": "David (Lost Boys) (larger)",
    "Jay2 The Inbetweeners.jpg": "Jay (The Inbetweeners) 2",
    "jeremy kyle jan 2013.jpg": "Jeremy Kyle",
    "Jon Snow-GoT.jpg": "Jon Snow",
    "Joffery geoffery  Baratheon - GoT.jpg": "Joffrey Baratheon",
    "Rhona)  Emmerdale.jpg": "Rhona (Emmerdale)",
    "lutenant hubert allo allo.jpg": "Lieutenant Hubert",
    "Paul Bazely as Troy Benidorm.jpg": "Paul Bazely (Troy)",
    "Max & OB Hollyoaks1.jpg": "Max and OB (Hollyoaks)",
})
WORD_FIX.update({"friers": "Faiers", "pheobe": "Phoebe", "walace": "Wallace"})
