# superfan title name -> (display name, short descriptor)
A = {
'ACDC':('AC/DC','hard rock legends'),'Abba':('ABBA','Swedish pop legends'),'Adele':('Adele','one of the great voices of our time'),
'Aerosmith':('Aerosmith','American rock legends'),'Alabama':('Alabama','country music favourites'),'Aretha Franklin':('Aretha Franklin','the Queen of Soul'),
'Ayumi Hamasaki':('Ayumi Hamasaki','the J-pop superstar'),'BZ':("B’z",'Japanese rock legends'),'Backstreet Boys':('Backstreet Boys','the boy band that never went away'),
'Barbra Streisand':('Barbra Streisand','the voice behind decades of hits'),'Barry Manilow':('Barry Manilow','the king of the big ballad'),'Barry White':('Barry White','the smoothest voice in soul'),
'Beach Boys':('The Beach Boys','sunshine harmonies from California'),'Beatles':('The Beatles','the Fab Four'),'Bee Gees':('Bee Gees','disco and harmony legends'),
'Beyonce':('Beyoncé','pop royalty'),'Billy Joel':('Billy Joel','the Piano Man himself'),'Black Eyed Peas':('Black Eyed Peas','party-starting hitmakers'),
'Bob Dylan':('Bob Dylan','the great songwriter'),'Bob Marley':('Bob Marley','reggae’s greatest name'),'Bon Jovi':('Bon Jovi','stadium rock favourites'),
'Brittney Spears':('Britney Spears','the pop princess'),'Bruce Springsteen':('Bruce Springsteen','the Boss'),'Bruno Mars':('Bruno Mars','the funk-pop showman'),
'Bryan Adams':('Bryan Adams','the rock ballad king'),'Carpenters':('Carpenters','soft-rock sweethearts'),'Celine Dion':('Celine Dion','the power ballad queen'),
'Cher':('Cher','the ultimate pop diva'),'Chicago':('Chicago','horn-driven rock legends'),'Chris Brown':('Chris Brown','the R&B star'),
'Coldplay':('Coldplay','stadium-filling Brit rockers'),'David Bowie':('David Bowie','music’s great chameleon'),'Def Leppard':('Def Leppard','Sheffield’s rock heroes'),
'Dire Straits':('Dire Straits','guitar rock greats'),'Earth Wind and Fire':('Earth, Wind & Fire','funk and soul legends'),'Ed Sheeran':('Ed Sheeran','the singer-songwriter from Suffolk'),
'Elvis Presley':('Elvis Presley','the King of Rock and Roll'),'Eminem':('Eminem','the rap legend'),'Eyna':('Enya','the queen of calm'),
'Fleetwood Mac':('Fleetwood Mac','classic rock royalty'),'Flo Rida':('Flo Rida','the party rapper'),'Foreigner':('Foreigner','classic rock hitmakers'),
'Frank Sinatra':('Frank Sinatra','Ol’ Blue Eyes'),'Garth Brooks':('Garth Brooks','the country superstar'),'Genesis':('Genesis','prog and pop rock greats'),
'George Michael':('George Michael','one of pop’s finest voices'),'George Strait':('George Strait','the King of Country'),"Guns 'n Roses":('Guns N’ Roses','hard rock heroes'),
'James Taylor':('James Taylor','the gentle singer-songwriter'),'Janet Jackson':('Janet Jackson','the pop and R&B icon'),'Jay Z':('Jay-Z','the hip hop mogul'),
'Johnny Cash':('Johnny Cash','the Man in Black'),'Johnny Hallyday':('Johnny Hallyday','France’s rock and roll star'),'Journey':('Journey','arena rock favourites'),
'Julio Iglesias':('Julio Iglesias','the romantic Spanish crooner'),'Justin Bieber':('Justin Bieber','the pop superstar'),'Justin Timberlake':('Justin Timberlake','the pop and R&B star'),
'Kanye West':('Kanye West','the rapper and producer'),'Katy Perry':('Katy Perry','the pop hitmaker'),'Kenny G':('Kenny G','the smooth sax star'),
'Kenny Rogers':('Kenny Rogers','the country storyteller'),'Kiss':('KISS','the face-painted rock band'),'Lady Gaga':('Lady Gaga','pop’s boldest star'),
'Led Zeppelin':('Led Zeppelin','rock gods'),'Lil Wayne':('Lil Wayne','the rap star'),'Linda Ronstadt':('Linda Ronstadt','the country-rock voice'),
'Linkin Park':('Linkin Park','nu-metal heroes'),'Lionel Richie':('Lionel Richie','the soul and ballad legend'),'Madonna':('Madonna','the Queen of Pop'),
'Mariah Carey':('Mariah Carey','the voice with the whistle notes'),'Maroon':('Maroon 5','pop-rock hitmakers'),'Meat Loaf':('Meat Loaf','the rock opera legend'),
'Metallica':('Metallica','metal giants'),'Michael Jackson':('Michael Jackson','the King of Pop'),'Neil Diamond':('Neil Diamond','the singalong legend'),
'Nicki Minaj':('Nicki Minaj','the rap queen'),'Nirvana':('Nirvana','grunge legends'),'Olivia Newton John':('Olivia Newton-John','the much-loved pop and musical star'),
'PINK':('P!nk','the pop-rock powerhouse'),'Paul Mccartney':('Paul McCartney','the songwriting great'),'Phil Collins':('Phil Collins','the drummer turned pop star'),
'Pink Floyd':('Pink Floyd','prog rock pioneers'),'Prince':('Prince','the purple genius'),'Queen':('Queen','British rock royalty'),
'REM':('R.E.M.','alternative rock favourites'),'Reba Mcentire':('Reba McEntire','the Queen of Country'),'Red Hot Chilli Peppers':('Red Hot Chili Peppers','funk-rock favourites'),
'Rihanna':('Rihanna','the pop and R&B superstar'),'Robbie Williams':('Robbie Williams','the ultimate British entertainer'),'Rod Stewart':('Rod Stewart','the raspy-voiced rock star'),
'Rolling Stones':('The Rolling Stones','rock and roll legends'),'Santana':('Santana','Latin rock guitar greats'),'Shania Twain':('Shania Twain','the country-pop queen'),
'Simon & Garfunkel':('Simon & Garfunkel','folk harmony legends'),'Stevie Wonder':('Stevie Wonder','the soul genius'),'Taylor Swift':('Taylor Swift','the record-breaking pop star'),
'The Doors':('The Doors','psychedelic rock legends'),'The Police':('The Police','new wave rock greats'),'The Who':('The Who','British rock legends'),
'Tina Turner':('Tina Turner','the Queen of Rock ’n’ Roll'),'Tom Petty':('Tom Petty','the heartland rock hero'),'Tupac Shakur':('Tupac Shakur','the rap legend'),
'Usher':('Usher','the R&B star'),'Van Halen':('Van Halen','guitar rock legends'),'Whitney Houston':('Whitney Houston','one of the greatest voices ever'),
}
# breed in title -> (display, trait line about the dog)
D = {
'Afghan Hound':('Afghan Hound','with that glamorous flowing coat'),'Akbash':('Akbash','the big, gentle flock guardian'),
'Beagle':('Beagle','with a nose that never switches off'),'Black Russian Terrier':('Black Russian Terrier','the big, bearded softie'),
'Border Collie':('Border Collie','the cleverest dog in the park'),'Borzoi':('Borzoi','elegant, graceful and very fast'),
'Bouvier Des Flandres':('Bouvier des Flandres','the shaggy Belgian farm dog'),'Broholmer':('Broholmer','the calm Danish giant'),
'Brussels Griffon':('Brussels Griffon','with the cheekiest little bearded face'),'Cairn Terrier':('Cairn Terrier','small, scruffy and full of character'),
'Canaan Dog':('Canaan Dog','alert, clever and loyal'),'Central Asian Shepherd':('Central Asian Shepherd','the big, brave guardian'),
'Cesky Terrior':('Cesky Terrier','the gentle Czech terrier'),'Chihuahua':('Chihuahua','tiny in size but huge in personality'),
'Cimarron':('Cimarrón Uruguayo','the tough Uruguayan working dog'),'Cuvac Dog':('Slovak Cuvac','the loyal white mountain dog'),
'Dalmatian':('Dalmatian','with those famous spots'),'Danish Pointer':('Danish Pointer','the friendly Danish gundog'),
'Danish Swedish Famdog':('Danish-Swedish Farmdog','the lively little farm dog'),'Deerhound':('Deerhound','the gentle, shaggy sighthound'),
'Dogo Argentino':('Dogo Argentino','the strong, loyal Argentinian'),'Dunker':('Dunker','the Norwegian scent hound'),
'East Siberian Laika':('East Siberian Laika','the hardy spitz from Siberia'),'Fila Bracilero':('Fila Brasileiro','the devoted Brazilian guardian'),
'Fox Cimarron':('Cimarrón','the tough South American working dog'),'Fox Paulistina':('Fox Paulistinha','the lively Brazilian terrier'),
'Fox Terrier':('Fox Terrier','bright, bouncy and always busy'),'Glen of Imaal':('Glen of Imaal Terrier','the tough little Irish terrier'),
'Gordon Retriever':('Gordon Retriever','the faithful family dog'),'Gordon Setter':('Gordon Setter','with that glossy black and tan coat'),
'Groenendael':('Groenendael','the elegant black Belgian Shepherd'),'Gull Terrier':('Gull Terrier','the strong, loyal terrier'),
'Gull Terrior':('Gull Terrier','the strong, loyal terrier'),'Hamiltonstovare':('Hamiltonstövare','the handsome Swedish hound'),
'Havanese':('Havanese','the fluffy little Cuban charmer'),'Icelandic Sheepdog':('Icelandic Sheepdog','the cheerful curly-tailed herder'),
'Inka Orchid':('Peruvian Inca Orchid','the elegant hairless hound'),'Irish Setter':('Irish Setter','with that stunning red coat'),
'Irish Terrior':('Irish Terrier','the bold, red-coated terrier'),'Irish water Spaniel':('Irish Water Spaniel','with those famous curls'),
'Jamthund':('Jämthund','the Swedish elkhound'),'Kangal':('Kangal','the calm, powerful Turkish guardian'),
'Karakachan':('Karakachan','the brave Bulgarian flock guardian'),'Keralian Beardog':('Karelian Bear Dog','the fearless Finnish hunter'),
'Kerry Blue':('Kerry Blue Terrier','with that soft blue-grey coat'),'Komondor':('Komondor','with that amazing corded coat'),
'Labrador':('Labrador','the friendliest dog going'),'Lapphund':('Lapphund','the fluffy reindeer herder'),
'Lundehund':('Lundehund','the extra-toed puffin dog from Norway'),'Malinois':('Malinois','the clever, hard-working Belgian Shepherd'),
'Mucuchies':('Mucuchíes','the Venezuelan mountain dog'),'Mudi Dog':('Mudi','the clever Hungarian herder'),
'Norwegian Elkhound':('Norwegian Elkhound','the hardy grey spitz'),'Pemeranian':('Pomeranian','the little ball of fluff'),
'Polish Hound':('Polish Hound','the steady, loyal scent hound'),'Pomeranian':('Pomeranian','the little ball of fluff'),
'Pug':('Pug','with the face nobody can say no to'),'Puli':('Puli','with those famous dreadlock cords'),
'Pumi':('Pumi','with the curly coat and perky ears'),'Red and white Setter':('Red and White Setter','the friendly Irish gundog'),
'Romanian Ravan Shepherd':('Romanian Raven Shepherd','the loyal mountain guardian'),'Rottweiler':('Rottweiler','the loyal softie with the tough-guy look'),
'Russkiy Toy':('Russkiy Toy','the tiny dog with big ears'),'Samoyed':('Samoyed','with that famous Sammy smile'),
'Schipperke':('Schipperke','the little black barge dog'),'Scottish Terrier':('Scottish Terrier','the proud little Scottie'),
'Shetland Sheepdog':('Shetland Sheepdog','the clever little Sheltie'),'Shiba Inu':('Shiba Inu','the fox-faced Japanese charmer'),
'Siberian Husky':('Siberian Husky','with those striking eyes'),'Slovakian Rough Pointer':('Slovakian Rough-haired Pointer','the bearded gundog'),
'South Russian Ovcharka':('South Russian Ovcharka','the big shaggy guardian'),'Sulimov':('Sulimov Dog','the rare Russian working dog'),
'Tervuren':('Tervuren','the striking Belgian Shepherd'),'Transyvanian Hound':('Transylvanian Hound','the hardy Hungarian hound'),
'Vallhund':('Swedish Vallhund','the little Viking herder'),'Vestie':('Westie','the cheeky little white terrier'),
'Vizsla':('Vizsla','the velcro dog that never leaves your side'),'Wheaten Terrior':('Wheaten Terrier','with the soft, silky wheaten coat'),
'Wolfhound':('Irish Wolfhound','the gentle giant'),'Xoloitzcuintle':('Xoloitzcuintle','the ancient Mexican hairless dog'),
}
