# predicate -> (category, keyword predicate (proper case), line about the person)
# placeholders: {she} {She} {her} {Her} {him} {girl} {woman}
T = {
# ---- has / is (traits) ----
'has a big car': ('trait','Has A Big Car',"drives something the size of a small bus and makes sure everyone in the car park knows it"),
'has a big dick': ('rude','Has A Big Dick',"isn’t shy about his reputation and finds this sort of joke hilarious"),
'has a dig bick': ('rude','Has A Dig Bick',"likes his jokes cheeky and his spoonerisms even cheekier"),
'has a problem': ('trait','Has A Problem',"always has something to moan about, usually before he’s had his first brew"),
'has a shit car': ('rude','Has A Shit Car',"drives a banger held together with gaffer tape and hope"),
'has a small car': ('trait','Has A Small Car',"squeezes into the tiniest parking spaces and still swears his little runaround is the best car on the road"),
'has a small dick': ('rude','Has A Small Dick',"can take a joke and has mates who never let him forget it"),
'is a cunt': ('rude','Is A Cunt',"has the kind of mates who show their love with very strong language"),
'is a sex godess': ('rude','Is A Sex Goddess',"knows exactly how fabulous she is"),
'is kinky': ('rude','Is Kinky',"has a cheeky side and a partner who knows all about it"),
'is loaded': ('trait','Is Loaded',"always seems to be getting the next round in, or at least says he will"),
'is mental': ('trait','Is Mental',"is the life and soul of every night out and never takes himself too seriously"),
'is muscular': ('trait','Is Muscular',"never skips a gym session and will happily tell you about his protein intake"),
'is old': ('trait','Is Old',"is getting on a bit and takes the birthday jokes in good spirit"),
'is retired': ('trait','Is Retired',"has finally hung up his work boots and now has all the time in the world for a cuppa"),
'is rich': ('trait','Is Rich',"likes the finer things in life and jokes about being rolling in it"),
'is ripped': ('trait','Is Ripped',"has worked hard for those abs and doesn’t mind showing them off"),
'is romantic': ('trait','Is Romantic',"never forgets an anniversary and always has flowers ready"),
'is single': ('trait','Is Single',"is happily single and wants the whole office to know it"),
'is swimming': ('trait','Is Swimming',"would rather be in the pool doing lengths than sitting at a desk"),
'is taken': ('trait','Is Taken',"is proudly off the market and happy to say so"),
'is thirsty': ('trait','Is Thirsty',"is always ready for the next brew, pint or anything else going"),
'is waiting': ('trait','Is Waiting',"is forever tapping his foot waiting for the kettle, the bus or everyone else"),
'is whipped': ('trait','Is Whipped',"does whatever his other half says and secretly loves it"),
'is young': ('trait','Is Young',"insists he’s still young at heart, whatever his birth certificate says"),
'looks like a cunt': ('rude','Looks Like A Cunt',"has mates who show their love with very strong language"),
# ---- dating apps (brands) ----
'is on bumble': ('dating','Is On Bumble',"is swiping away on Bumble and doesn’t mind who knows it"),
'is on grinder': ('dating','Is On Grindr',"is on Grindr and has a sense of humour about it"),
'is on match': ('dating','Is On Match',"is giving online dating a go on Match"),
'is on pof': ('dating','Is On POF',"has a Plenty of Fish profile and plenty of stories to go with it"),
'is on tinder': ('dating','Is On Tinder',"spends more time swiping on Tinder than doing actual work"),
'is premiumn on bumble': ('dating','Is Premium On Bumble',"has paid for the premium Bumble upgrade and is taking dating seriously"),
'is premiumn on pof': ('dating','Is Premium On POF',"has gone premium on Plenty of Fish and wants results"),
'is premiumn on tinder': ('dating','Is Premium On Tinder',"has splashed out on a premium Tinder account and isn’t ashamed"),
'is shagging on bumble': ('datingrude','Is Shagging On Bumble',"has had a lot of luck on Bumble lately"),
'is shagging on grinder': ('datingrude','Is Shagging On Grindr',"has had plenty of luck on Grindr lately"),
'is shagging on pof': ('datingrude','Is Shagging On POF',"has had plenty of luck on Plenty of Fish lately"),
'is shagging on tinder': ('datingrude','Is Shagging On Tinder',"has had a very good run on Tinder lately"),
'is smashing on bumble': ('datingrude','Is Smashing On Bumble',"has been doing very nicely on Bumble lately"),
'loves bumble': ('dating','Loves Bumble',"is never far from the Bumble app and loves a good swipe"),
'loves babestation': ('datingrude','Loves Babestation',"has a cheeky late-night TV habit his mates won’t let him forget"),
# ---- rude ----
'loves anal': ('rude','Loves Anal',"has a filthy sense of humour and friends to match"),
'loves boobs': ('rude','Loves Boobs',"isn’t shy about what catches his eye"),
'loves cock': ('rude','Loves Cock',"has a filthy sense of humour and friends to match"),
'loves to have sex': ('rude','Loves To Have Sex',"has a cheeky side and isn’t afraid to show it"),
'loves to shag': ('rude','Loves To Shag',"has a cheeky side and a very knowing smile"),
'wants anal': ('rude','Wants Anal',"has a seriously cheeky sense of humour"),
'wants fingering': ('rude','Wants Fingering',"has a seriously cheeky sense of humour"),
'wants licking': ('rude','Wants Licking',"loves a saucy joke"),
'wants licking out': ('rude','Wants Licking Out',"has the rudest sense of humour in the office"),
'wants oral': ('rude','Wants Oral',"isn’t shy about saying what she wants"),
'wants sex': ('rude','Wants Sex',"isn’t shy about saying what she wants"),
'wants to fuck': ('rude','Wants To Fuck',"says exactly what she thinks, swear words and all"),
'loves legs': ('cheeky','Loves Legs',"is a self-confessed leg man"),
# ---- "type" ----
'loves black men': ('type','Loves Black Men',"knows exactly what her type is"),
'loves fat men': ('type','Loves Fat Men',"likes a man with something to cuddle"),
'loves guys': ('type','Loves Guys',"loves the lads and is proud of it"),
'loves tall girls': ('type','Loves Tall Girls',"has always gone for tall women"),
# ---- relations ----
'loves her allotment': ('hobby','Loves Her Allotment',"spends every spare hour at her allotment plot"),
'loves her best friend': ('relation','Loves Her Best Friend',"would do anything for her best friend"),
'loves her boyfriend': ('relation','Loves Her Boyfriend',"is head over heels for her boyfriend"),
'loves her dad': ('relation','Loves Her Dad',"thinks her dad is the best there is"),
'loves her girlfriend': ('relation','Loves Her Girlfriend',"is head over heels for her girlfriend"),
'loves her husband': ('relation','Loves Her Husband',"still adores her husband after all these years"),
'loves her mum': ('relation','Loves Her Mum',"thinks her mum is the best in the world"),
'loves his wife': ('relation','Loves His Wife',"adores his wife and isn’t afraid to say so"),
'loves kids': ('relation','Loves Kids',"is brilliant with children, whether he’s a dad, uncle, teacher or coach"),
'loves romance': ('relation','Loves Romance',"is a hopeless romantic at heart"),
# ---- faith ----
'loves allah': ('faith','Loves Allah',"draws strength from her faith every single day"),
'loves god': ('faith','Loves God',"keeps faith at the centre of {her} life"),
'loves jesus': ('faith','Loves Jesus',"keeps faith at the centre of his life"),
# ---- places ----
'loves asia': ('place','Loves Asia',"has fallen for Asia’s food, cities and beaches"),
'loves china': ('place','Loves China',"is fascinated by China’s food, history and culture"),
'loves egypt': ('place','Loves Egypt',"can’t get enough of Egypt, from the pyramids to the Red Sea"),
'loves england': ('place','Loves England',"is proud to be English and never misses a match day"),
'loves france': ('place','Loves France',"dreams of croissants, vineyards and long French holidays"),
'loves germany': ('place','Loves Germany',"loves everything about Germany, from the Christmas markets to the beer halls"),
'loves scotland': ('place','Loves Scotland',"is proud of Scotland, its glens and its people"),
'loves hollidays': ('place','Loves Holidays',"is always counting down to the next holiday"),
'loves to travel': ('place','Loves To Travel',"always has the next trip booked"),
'loves cruising': ('place','Loves Cruising',"has caught the cruise bug and is already planning the next sailing"),
# ---- music ----
'loves grime': ('music','Loves Grime',"has grime on repeat"),
'loves hip hop': ('music','Loves Hip Hop',"lives for hip hop beats"),
'loves jazz': ('music','Loves Jazz',"would happily spend every evening in a jazz bar"),
'loves music': ('music','Loves Music',"always has music playing"),
'loves pop': ('music','Loves Pop',"knows every word of every pop chart hit"),
'loves punk': ('music','Loves Punk',"still has a punk spirit, whatever the dress code at work says"),
'loves rap': ('music','Loves Rap',"knows every bar of {her} favourite rap tracks"),
'loves rock': ('music','Loves Rock',"turns the rock music up loud"),
'loves to rave': ('music','Loves To Rave',"lives for a rave and a big night out"),
'loves dance': ('hobby','Loves Dance',"is always first on the dance floor"),
'loves dancing': ('hobby','Loves Dancing',"can’t keep still when the music starts"),
'loves ballet dancing': ('hobby','Loves Ballet Dancing',"lives for ballet class"),
'loves burlesque dancing': ('hobby','Loves Burlesque Dancing',"loves the glamour and sparkle of burlesque"),
'loves ceilidh dancing': ('hobby','Loves Ceilidh Dancing',"is first up for every ceilidh"),
# ---- celebs / brands in "loves" ----
'loves 5sos': ('celeb','Loves 5SOS',"has 5 Seconds of Summer on repeat"),
'loves beyonce': ('celeb','Loves Beyoncé',"knows every Beyoncé dance routine"),
'loves dr. dre': ('celeb','Loves Dr. Dre',"rates Dr. Dre as the greatest producer going"),
'loves drake': ('celeb','Loves Drake',"has Drake on repeat"),
'loves eminem': ('celeb','Loves Eminem',"can rap along to Eminem word for word"),
'loves honey g': ('celeb','Loves Honey G',"still hasn’t got over Honey G on the telly"),
'loves ac cars': ('brand','Loves AC Cars',"dreams of classic AC sports cars"),
"loves cadillac's": ('brand','Loves Cadillacs',"loves big American Cadillacs"),
"loves chevrolet's": ('brand','Loves Chevrolets',"is mad about Chevrolets"),
"loves ford's": ('brand','Loves Fords',"has always been a Ford fan"),
"loves honda's": ('brand','Loves Hondas',"swears by Hondas"),
'loves audis': ('brand','Loves Audis',"is an Audi fan through and through"),
'loves iphones': ('brand','Loves iPhones',"is never more than an arm’s length from an iPhone"),
'loves facebook': ('brand','Loves Facebook',"is always scrolling Facebook"),
'loves twititer': ('brand','Loves Twitter',"is always on Twitter with an opinion"),
'loves kfc': ('brand','Loves KFC',"never says no to a KFC bucket"),
'loves mc donalds': ('brand','Loves McDonald’s',"knows the McDonald’s menu off by heart"),
'loves nandos': ('brand','Loves Nando’s',"knows exactly how hot {she} likes {her} Nando’s"),
'loves subway': ('brand','Loves Subway',"has a Subway order off by heart"),
'loves crossfit': ('brandsport','Loves CrossFit',"never misses a CrossFit session"),
# ---- sports ----
'loves aquatics': ('sport','Loves Aquatics',"is happiest in the water"),
'loves archery': ('sport','Loves Archery',"has a steady hand and an eye on the gold"),
'loves athletics': ('sport','Loves Athletics',"lives for the track and field"),
'loves badminton': ('sport','Loves Badminton',"never misses club night at the badminton courts"),
'loves basketball': ('sport','Loves Basketball',"is always shooting hoops"),
'loves biking': ('sport','Loves Biking',"is never happier than on two wheels"),
'loves bmxing': ('sport','Loves BMXing',"spends every spare hour at the BMX track"),
'loves bowls': ('sport','Loves Bowls',"is a regular on the bowling green"),
'loves boxing': ('sport','Loves Boxing',"never misses a training session or a big fight night"),
'loves camogie': ('sport','Loves Camogie',"lives for camogie"),
'loves canoeing': ('sport','Loves Canoeing',"is happiest out on the water with a paddle"),
'loves cricket': ('sport','Loves Cricket',"spends summer weekends at the cricket club"),
'loves cycling': ('sport','Loves Cycling',"clocks up the miles on the bike every weekend"),
'loves darts': ('sport','Loves Darts',"is never far from the oche"),
'loves diving': ('sport','Loves Diving',"is happiest exploring underwater"),
'loves fencing': ('sport','Loves Fencing',"loves the speed and skill of fencing"),
'loves flying': ('hobby','Loves Flying',"is happiest in the air"),
'loves flying aerobatics': ('hobby','Loves Flying Aerobatics',"loves loops, rolls and stunt flying"),
'loves footy': ('sport','Loves Footy',"lives for football, whether it’s playing on a Sunday or watching on the telly"),
'loves golf': ('sport','Loves Golf',"would spend every day on the golf course if {she} could"),
'loves to golf': ('sport','Loves To Golf',"would be out on the fairway every day if she could"),
'loves gymnastics': ('sport','Loves Gymnastics',"lives for gymnastics"),
'loves handball': ('sport','Loves Handball',"loves the pace of handball"),
'loves hiking': ('sport','Loves Hiking',"is happiest in walking boots out on the hills"),
'loves hockey': ('sport','Loves Hockey',"never misses a hockey match"),
'loves ice hockey': ('sport','Loves Ice Hockey',"loves the speed and crunch of ice hockey"),
'loves ice skating': ('sport','Loves Ice Skating',"is happiest gliding round the ice rink"),
'loves judo': ('sport','Loves Judo',"never misses a judo session"),
'loves jujitsu': ('sport','Loves Jujitsu',"lives for jujitsu training"),
'loves karate': ('sport','Loves Karate',"never misses a karate class"),
'loves lifting': ('sport','Loves Lifting',"lives for the weights room"),
'loves paddling': ('sport','Loves Paddling',"is happiest out paddling on the water"),
'loves playing football': ('sport','Loves Playing Football',"is always out playing football"),
'loves playing hockey': ('sport','Loves Playing Hockey',"is always out on the hockey pitch"),
'loves racing': ('sport','Loves Racing',"lives for motorsport and race days"),
'loves riding': ('sport','Loves Riding',"is happiest out riding"),
'loves rowing': ('sport','Loves Rowing',"is up at dawn for rowing training"),
'loves rugby': ('sport','Loves Rugby',"lives for rugby, on the pitch or in the stands"),
'loves running': ('sport','Loves Running',"is always out pounding the pavements"),
'loves sailing': ('sport','Loves Sailing',"is happiest out on the water with the wind in the sails"),
'loves skiing': ('sport','Loves Skiing',"counts down the days to the next ski trip"),
'loves sports': ('sport','Loves Sports',"loves any kind of sport, playing or watching"),
'loves swimming': ('sport','Loves Swimming',"never misses an early swim"),
'loves table tennis': ('sport','Loves Table Tennis',"is a demon at the table tennis table"),
'loves tennis': ('sport','Loves Tennis',"is always on the tennis court"),
'loves the gym': ('sport','Loves The Gym',"never misses a gym session"),
'loves tiquando': ('sport','Loves Taekwondo',"never misses a taekwondo class"),
'loves track cycling': ('sport','Loves Track Cycling',"loves the speed of the velodrome"),
'loves triathalons': ('sport','Loves Triathlons',"swims, bikes and runs for fun"),
'loves volleyball': ('sport','Loves Volleyball',"loves volleyball, indoors or on the beach"),
'loves waterpolo': ('sport','Loves Water Polo',"loves the rough and tumble of water polo"),
'loves westling': ('sport','Loves Wrestling',"loves wrestling, in the ring or on the telly"),
'loves wrestling': ('sport','Loves Wrestling',"never misses a wrestling night"),
'padel is my hobby': ('sport','Padel Is My Hobby',"has caught the padel bug and books a court every chance {she} gets"),
'wants to dive': ('sport','Wants To Dive',"is itching to get back under the waves"),
# ---- hobbies / work ----
'loves camping': ('hobby','Loves Camping',"would rather be in a tent than a hotel"),
'loves cars': ('hobby','Loves Cars',"is a petrolhead through and through"),
'loves cartoons': ('hobby','Loves Cartoons',"still loves curling up with cartoons"),
'loves combines': ('hobby','Loves Combines',"loves harvest time and the big combine harvesters"),
'loves crochet': ('hobby','Loves Crochet',"always has a crochet hook in hand"),
'loves dice': ('hobby','Loves Dice',"loves a board game night and a roll of the dice"),
'loves diggers': ('hobby','Loves Diggers',"loves diggers and big machines"),
'loves engineering': ('hobby','Loves Engineering',"loves taking things apart to see how they work"),
'loves fashion': ('hobby','Loves Fashion',"always looks the part"),
'loves flower arranging': ('hobby','Loves Flower Arranging',"has a real eye for a beautiful bouquet"),
'loves gaming': ('hobby','Loves Gaming',"is happiest with a controller in hand"),
'loves gardening': ('hobby','Loves Gardening',"is happiest out in the garden"),
'loves inspecting': ('hobby','Loves Inspecting',"has an eye for detail that never misses a thing"),
'loves texting': ('hobby','Loves Texting',"is never off {her} phone"),
'loves to work': ('hobby','Loves To Work',"is first in and last out at work"),
'loves to sleep': ('hobby','Loves To Sleep',"would hit snooze all day if she could"),
'loves to party': ('hobby','Loves To Party',"is always first on the guest list"),
'wants to party': ('hobby','Wants To Party',"is always ready for a party"),
'loves bubbles': ('hobby','Loves Bubbles',"loves a glass of bubbly"),
'loves christmas': ('hobby','Loves Christmas',"has the decorations up the moment December arrives"),
'loves easter': ('hobby','Loves Easter',"loves Easter, the egg hunts and the chocolate"),
'loves money': ('hobby','Loves Money',"always has an eye on {her} bank balance"),
'wants money': ('hobby','Wants Money',"is always dreaming of a lottery win"),
'wants to date': ('hobby','Wants To Date',"is ready to find love"),
'wants to toast': ('hobby','Wants To Toast',"is always first to raise a glass"),
'wants caring': ('hobby','Wants Caring',"could do with a bit of looking after"),
'wants loving': ('hobby','Wants Loving',"could do with a bit more love"),
'wants a baby': ('hobby','Wants A Baby',"is dreaming of starting a family"),
'wants a new car': ('hobby','Wants A New Car',"has been browsing car adverts for months"),
# ---- animals ----
'loves animals': ('animal','Loves Animals',"stops to stroke every dog {she} passes"),
'loves bats': ('animal','Loves Bats',"heads out at dusk with a bat detector and thinks bats are brilliant"),
'loves birds': ('animal','Loves Birds',"always has binoculars handy and knows every bird on the feeder"),
'loves bunnies': ('animal','Loves Bunnies',"has a soft spot for rabbits and their floppy ears"),
'loves cats': ('animal','Loves Cats',"is a cat lover through and through"),
'loves chickens': ('animal','Loves Chickens',"keeps a few hens in the garden and loves fresh eggs"),
'loves dogs': ('animal','Loves Dogs',"loves dogs more than most people"),
'loves fish': ('animal','Loves Fish',"spends hours looking after the fish tank or the garden pond"),
'loves foxes': ('animal','Loves Foxes',"gets excited every time a fox trots across the garden"),
'loves frogs': ('animal','Loves Frogs',"counts the frogspawn in the pond every spring"),
'loves goats': ('animal','Loves Goats',"thinks goats are the funniest animals on the farm"),
'loves hippos': ('animal','Loves Hippos',"heads straight for the hippos at every zoo"),
'loves horses': ('animal','Loves Horses',"is happiest at the yard and smells faintly of hay most weekends"),
'loves monkeys': ('animal','Loves Monkeys',"thinks monkeys are the cheekiest animals going"),
'loves pandas': ('animal','Loves Pandas',"melts at every video of a panda rolling around"),
'loves pigs': ('animal','Loves Pigs',"thinks pigs are the cleverest animals on the farm"),
'loves shark': ('animal','Loves Sharks',"is fascinated by sharks and never misses a shark documentary"),
'loves sheep': ('animal','Loves Sheep',"loves sheep, whether {she} farms them or just counts them"),
'loves spiders': ('animal','Loves Spiders',"is the one everyone calls when there’s a spider in the bath"),
'loves zebra': ('animal','Loves Zebras',"thinks zebras are the best-dressed animals on the planet"),
'wants a cat': ('animal','Wants A Cat',"is desperate for a cat"),
'wants a dog': ('animal','Wants A Dog',"is desperate for a dog"),
'wants cats': ('animal','Wants Cats',"wants a house full of cats"),
'wants dogs': ('animal','Wants Dogs',"wants a house full of dogs"),
'wants puppies': ('animal','Wants Puppies',"melts at the sight of a puppy"),
# ---- food ----
'loves apples':('food','Loves Apples',''),'loves apricots':('food','Loves Apricots',''),'loves asparagus':('food','Loves Asparagus',''),
'loves bacon':('food','Loves Bacon',''),'loves baked beans':('food','Loves Baked Beans',''),'loves beetroot':('food','Loves Beetroot',''),
'loves berries':('food','Loves Berries',''),'loves biscuits':('food','Loves Biscuits',''),'loves bread':('food','Loves Bread',''),
'loves brown sauce':('food','Loves Brown Sauce',''),'loves burgers':('food','Loves Burgers',''),'loves carrots':('food','Loves Carrots',''),
'loves cassava':('food','Loves Cassava',''),'loves cauliflower':('food','Loves Cauliflower',''),'loves celery':('food','Loves Celery',''),
'loves cereal bars':('food','Loves Cereal Bars',''),'loves cheese':('food','Loves Cheese',''),'loves cherries':('food','Loves Cherries',''),
'loves chicken':('food','Loves Chicken',''),'loves chips':('food','Loves Chips',''),'loves chocolate':('food','Loves Chocolate',''),
'loves chorizo':('food','Loves Chorizo',''),'loves cream':('food','Loves Cream',''),'loves cream cheese':('food','Loves Cream Cheese',''),
'loves croissants':('food','Loves Croissants',''),'loves crumpets':('food','Loves Crumpets',''),'loves curry':('food','Loves Curry',''),
'loves eggs':('food','Loves Eggs',''),'loves fajitas':('food','Loves Fajitas',''),'loves food':('food','Loves Food',''),
'loves hot dogs':('food','Loves Hot Dogs',''),'loves ice cream':('food','Loves Ice Cream',''),'loves kebab':('food','Loves Kebabs',''),
'loves ketchup':('food','Loves Ketchup',''),'loves lasagne':('food','Loves Lasagne',''),'loves mayonaise':('food','Loves Mayonnaise',''),
'loves muffins':('food','Loves Muffins',''),'loves pizza':('food','Loves Pizza',''),'loves pork':('food','Loves Pork',''),
'loves sausage':('food','Loves Sausages',''),'loves shushi':('food','Loves Sushi',''),'loves soup':('food','Loves Soup',''),
'loves sweet chilli':('food','Loves Sweet Chilli',''),'loves toast':('food','Loves Toast',''),'loves to eat':('food','Loves To Eat',''),
'wants dinner':('food','Wants Dinner',''),'wants food':('food','Wants Food',''),
# ---- drink ----
'loves beer':('drink','Loves Beer',''),'loves coffee':('drink','Loves Coffee',''),'loves green tea':('drink','Loves Green Tea',''),
'loves tea':('drink','Loves Tea',''),'loves drinking':('drink','Loves Drinking',''),'loves to drink':('drink','Loves To Drink',''),
'wants coffee':('drink','Wants Coffee',''),'wants tea':('drink','Wants Tea',''),
}
# owner should decide: ambiguous or risky slogans – no copy written
SKIP = {
 'loves small girls': 'Slogan could read as sexualising children on an ADULT mug – owner to review/withdraw',
 'loves dt': 'Meaning of "DT" unclear (person? brand?) – owner to confirm',
 'loves game': 'Meaning unclear (game meat, gaming or the rapper The Game?) – owner to confirm',
 'loves ball': 'Meaning unclear – owner to confirm',
 'loves breeding': 'Meaning unclear (animal breeding or adult joke?) – owner to confirm',
 'looks good for': 'Slogan is incomplete ("looks good for [age]?") and there is no option to add an age – owner to confirm',
 'loves to sleep swim': 'Slogan "sleep swim" unclear – owner to confirm',
 'loves table shooting': 'Meaning of "table shooting" unclear – owner to confirm',
}
# food/drink lines: one per item, written out
FOODLINE = {
'Apples':"never leaves the house without an apple in {her} bag",'Apricots':"keeps a jar of apricots on the go",'Asparagus':"counts down to British asparagus season every spring",
'Bacon':"thinks every breakfast needs bacon",'Baked Beans':"thinks beans on toast is the perfect meal",'Beetroot':"puts beetroot in everything",
'Berries':"always has a punnet of berries on the go",'Biscuits':"never has a cuppa without dunking a biscuit",'Bread':"can’t resist fresh bread",
'Brown Sauce':"puts brown sauce on every bacon butty",'Burgers':"knows where to find the best burger in town",'Carrots':"crunches carrots like a rabbit",
'Cassava':"loves cooking with cassava",'Cauliflower':"swears cauliflower cheese is a food group",'Celery':"is always crunching on celery",
'Cereal Bars':"always has a cereal bar in {her} bag",'Cheese':"never says no to a cheeseboard",'Cherries':"loves fresh cherries",
'Chicken':"orders chicken every time",'Chips':"never says no to a portion of chips",'Chocolate':"always has a secret chocolate stash",
'Chorizo':"puts chorizo in everything",'Cream':"likes lashings of cream on every pudding",'Cream Cheese':"spreads cream cheese on every bagel",
'Croissants':"thinks breakfast isn’t breakfast without a croissant",'Crumpets':"loves hot buttered crumpets",'Curry':"thinks every Friday is curry night",
'Eggs':"loves eggs any way",'Fajitas':"thinks every week needs a fajita night",'Food':"is always thinking about {her} next meal",
'Hot Dogs':"never walks past a hot dog stand",'Ice Cream':"has ice cream whatever the weather",'Kebabs':"knows the best kebab shop in town",
'Ketchup':"puts ketchup on everything",'Lasagne':"thinks lasagne is the best tea there is",'Mayonnaise':"puts mayo on everything",
'Muffins':"always has a muffin with {her} coffee",'Pizza':"thinks every night is pizza night",'Pork':"loves a Sunday roast pork",
'Sausages':"loves a good sausage sandwich",'Sushi':"is a sushi fan",'Soup':"always has a pan of soup on the go",
'Sweet Chilli':"puts sweet chilli sauce on everything",'Toast':"lives on toast",'Eat':"lives to eat and is already planning the next meal",'Dinner':"is always asking what’s for tea",
'Food ':"",
'Beer':"loves a pint down the local",'Coffee':"can’t function without coffee",'Green Tea':"swears by green tea",'Tea':"is always putting the kettle on",
'Drinking':"is always first to the bar",'Drink':"loves a drink and a good night out",
}
