P='gid://shopify/Product/'
# id: (Name, role, uses, h2tail, bullet, closing, meta_uses, seo_tail, pron, estate)
S={
'9369893512':('Rolf Harris','the former Australian-born TV entertainer and painter','satire, theatre productions and TV-era themed fancy dress','Satire and Theatre','A simple costume piece for sketches set in the golden age of British TV','This TV-era face mask is aimed at drama groups, satirists and adult retro-themed events','satire, theatre and TV-era fancy dress','for Satire','him',True),
'9369909064':('Stuart Hall','the former British TV and radio presenter','satirical sketches, stage productions and retro TV-themed fancy dress','Theatre and Satire','A low-cost costume piece for sketches about British television','This presenter face mask is intended for drama groups, satirists and adult themed events','satire, stage productions and retro TV fancy dress','for Theatre','him',True),
'8283952906491':('Reggie Kray','one of the Kray twins from 1960s London','historical drama, stage productions and 1960s-themed fancy dress','Historical Drama and Theatre','A cheap, reliable prop for plays and films set in 1960s London','This 1960s face mask is aimed at drama groups and adult history events','historical drama, theatre and 1960s fancy dress','for Drama','him',True),
'8283953135867':('Ronnie Kray','one of the Kray twins from 1960s London','period drama, theatre productions and 1960s-themed fancy dress','Period Drama and Theatre','A simple costume piece for stage plays set in the East End of the 1960s','This period face mask is intended for drama groups and adult history events','period drama, theatre and 1960s fancy dress','for Drama','him',True),
'8289356742907':('Jeffrey Epstein','the late American financier','satire, theatre productions and political sketches','Satire and Theatre','A simple costume piece for satirical sketches and stage plays','This face mask is aimed at drama groups and adult satire events','satire, theatre and political sketches','for Satire','him',True),
'14834575409533':('Jeffrey Epstein','the late American financier','satirical sketches, stage productions and political theatre','Theatre and Satire','A low-cost prop for satirical theatre and sketch shows','This face mask is intended for drama groups and adult satire events','satirical sketches and political theatre','for Theatre','him',True),
'15042721218941':('Jeffrey Epstein','the late American financier, shown in a second photo','satire, sketch comedy and political theatre','Satire and Sketches','A cheap costume piece for political sketches and satire','This second-design face mask is aimed at drama groups and adult satire events','satire, sketch comedy and political theatre','for Satire','him',True),
'15865897288061':('Evil Epstein','a caricature design depicting the late American financier Jeffrey Epstein','political satire, sketch shows and theatre','Political Satire','A simple prop for political sketches and satirical theatre','This caricature face mask is aimed at satirists and adult drama groups','political satire, sketch shows and theatre','for Satire','him',True),
'8475064434939':('OJ Simpson','the former American football player and actor','satire, theatre productions and 1990s-themed fancy dress','Satire and Theatre','A simple costume piece for sketches and plays set in the 1990s','This 1990s face mask is aimed at drama groups, satirists and adult themed events','satire, theatre and 1990s fancy dress','for Satire','him',True),
'14834568331645':('Bill Cosby','the American comedian and actor','satire, theatre productions and retro TV-themed fancy dress','Satire and Theatre','A simple costume piece for sketches set in 1980s American TV','This retro TV face mask is aimed at drama groups, satirists and adult themed events','satire, theatre and retro TV fancy dress','for Satire','him',False),
'15030278324605':('Bill Cosby','the American comedian and actor','satirical sketches, stage productions and 1980s-themed fancy dress','Theatre and Satire','A low-cost prop for sketch shows and stage plays','This face mask is intended for drama groups, satirists and adult themed events','sketches, stage plays and 1980s fancy dress','for Theatre','him',False),
'4328386822219':('Bill Cosby','the American comedian and actor','satire, sketch comedy and theatre productions','Satire and Sketches','A cheap costume piece for satirical sketches','This face mask is aimed at satirists and adult drama groups','satire, sketch comedy and theatre productions','for Satire','him',False),
'15050006790525':('R Kelly','the American R&amp;B singer','satire, theatre productions and music-themed sketches','Satire and Theatre','A simple costume piece for satirical sketches about the music industry','This face mask is aimed at drama groups, satirists and adult themed events','satire, theatre and music-themed sketches','for Satire','him',False),
'15660493832573':('Ed Gein','the American whose case inspired several horror films','true-crime drama, theatre productions and horror film study nights for adults','True-Crime Drama and Theatre','A low-cost prop for stage and screen drama projects','This face mask is aimed at drama groups and adult film societies','true-crime drama, theatre and adult film study nights','for Drama','him',True),
'15660494651773':('Jeffrey Dahmer','the American subject of several true-crime documentaries and dramas','true-crime drama and theatre productions','True-Crime Drama and Theatre','A simple prop for stage and student film projects','This face mask is aimed at drama groups and adult film societies','true-crime drama and theatre productions','for Drama','him',True),
'9438733000':('Osama Bin Laden','the former al-Qaeda leader','historical drama, political satire and theatre productions','Historical Drama and Satire','A cheap, reliable prop for political sketches and drama','This historical figure mask is aimed at drama groups, satirists and adult history events','historical drama, political satire and theatre','for Drama','him',True),
'9438733768':('Prince Andrew','the former working member of the British royal family','political and royal satire, sketch shows and theatre productions','Royal Satire and Theatre','A simple costume piece for satirical sketches about the royals','This face mask is aimed at satirists, drama groups and adult themed events','royal satire, sketch shows and theatre','for Satire','him',False),
'9438734792':('Vladimir Putin','the Russian president','political satire, sketch shows and theatre productions','Political Satire','A cheap, reliable prop for political sketches and satire','This political figure mask is aimed at satirists and adult drama groups','political satire, sketch shows and theatre','for Satire','him',False),
'9438745288':('Vladimir Putin','the Russian president','satirical sketches, political theatre and drama productions','Satire and Political Theatre','A low-cost prop for political comedy and stage satire','This face mask is intended for satirists and adult drama groups','satirical sketches, political theatre and drama','for Satire','him',False),
'9438735048':('Kim Jong Un','the North Korean leader','political satire, sketch shows and theatre productions','Political Satire','A cheap, reliable prop for political sketches and satire','This political figure mask is aimed at satirists and adult drama groups','political satire, sketch shows and theatre','for Satire','him',False),
'9438735240':('Kim Jong Il','the former North Korean leader','historical drama, political satire and theatre productions','Historical Drama and Satire','A simple costume piece for political sketches and drama','This historical figure mask is aimed at satirists and adult drama groups','historical drama, political satire and theatre','for Satire','him',True),
'9438739720':('Kim Jong Il','the former North Korean leader','political satire, historical drama and stage productions','Satire and Historical Drama','A low-cost prop for satirical theatre and sketches','This face mask is intended for satirists, drama groups and adult history events','political satire, historical drama and the stage','for Satire','him',True),
'9438736840':('Bashar al-Assad','the former Syrian president','political satire, sketch shows and theatre productions','Political Satire','A cheap, reliable prop for political sketches and satire','This political figure mask is aimed at satirists and adult drama groups','political satire, sketch shows and theatre','for Satire','him',False),
'9438739912':('Leon Trotsky','the Russian revolutionary','historical drama, theatre productions and history-themed events','Historical Drama and Theatre','A cheap, reliable prop for plays set in early 20th-century Russia','This historical figure mask is aimed at drama groups and adult history events','historical drama, theatre and history events','for Drama','him',True),
'9438745416':('Adolf Hitler','the Nazi German dictator','historical drama, theatre productions and satirical sketches','Historical Drama and Satire','A cheap, reliable prop for WWII-era plays and satirical sketches','This historical figure mask is aimed at drama groups, satirists and adult history events','historical drama, theatre and satirical sketches','for Drama','him',True),
'9438755912':('Adolf Hitler','the Nazi German dictator in a colour design','historical drama, satire and WWII-era theatre productions','Drama and Satire','A low-cost prop for wartime plays and satire','This historical figure mask is intended for drama groups, satirists and adult history events','historical drama, satire and WWII-era theatre','for Drama','him',True),
'9530645512':('Jonathan King','the former British pop producer and TV presenter','satire, theatre productions and retro pop-themed sketches','Satire and Theatre','A simple costume piece for sketches about the 1970s pop scene','This retro pop face mask is aimed at drama groups, satirists and adult themed events','satire, theatre and retro pop sketches','for Satire','him',False),
'9530628104':('Josef Fritzl','the Austrian man who was the subject of a widely reported 2008 court case','true-crime drama and theatre productions for adults','True-Crime Drama','A simple prop for stage and student film projects','This face mask is aimed at drama groups and adult film societies','true-crime drama and theatre productions','for Drama','him',False),
'9530645704':('Josef Fritzl','the Austrian man who was the subject of a widely reported 2008 court case, shown in a second photo','drama productions and theatre for adults','Drama and Theatre','A low-cost prop for stage drama projects','This second-design face mask is intended for drama groups and adult film societies','drama productions and theatre','for Drama','him',False),
'4328405794891':('P Diddy','the American rapper and record producer','satire, theatre productions and music-themed sketches','Satire and Theatre','A simple costume piece for satirical sketches about the music industry','This face mask is aimed at drama groups, satirists and adult themed events','satire, theatre and music-themed sketches','for Satire','him',False),
}
S={P+k:v for k,v in S.items()}
SEONAME={'Jeffrey Epsteinthe late American financier, shown in a second photo':'Jeffrey Epstein 2','Josef Fritzlthe Austrian man who was the subject of a widely reported 2008 court case, shown in a second photo':'Josef Fritzl 2'}
def build(v):
    name,role,uses,h2t,bullet,closing,muses,stail,pron,estate=v
    first='Each mask is digitally printed on 350gsm silk card, cut around the face, with the eye holes already cut out. Thread the elastic through, tie it to fit and it\'s ready for rehearsal or the stage. Need a face we don\'t list? We can make a custom mask from your own photo, so call us on 01439 771468.'
    d=(f"<p>This {name} face mask shows {role}, printed in full colour on thick card and cut to shape. It's intended for {uses}{'' if uses.endswith('for adults') else ' for adults'}.</p>\n"
       f"<h2>{name} Face Mask for {h2t}</h2>\n<p>{first}</p>\n<h3>Why you'll love it</h3>\n<ul>\n"
       f"<li>Full A4 size (297 x 210 mm), so it covers an adult face</li>\n<li>{bullet}</li>\n<li>Lightweight card is easy to wear and remove between scenes</li>\n"
       f"<li>Thick 350gsm silk card that keeps its shape under stage lights</li>\n<li>Semi-waterproof finish for repeated use in rehearsals</li>\n</ul>\n"
       f"<h3>Size &amp; details</h3>\n<ul>\n<li>Size: 297 x 210 mm (A4), a full adult-size face</li>\n<li>Material: 350gsm silk card, full-colour digital print</li>\n"
       f"<li>Finish: semi-waterproof</li>\n<li>Fit: one size for adults; elastic included</li>\n<li>Pre-cut eye holes; cut to the shape of the face</li>\n<li>Packaging: board-backed envelope</li>\n</ul>\n"
       f"<h3>Delivery</h3>\n<p>Printed in-house at our North Yorkshire workshop and posted to you flat in a board-backed envelope. Dispatch and postage options are shown at checkout.</p>\n"
       f"<p>{closing}.</p>\n<h3>Please note</h3>\n"
       f"<p class=\"disclaimer\">This is an unofficial novelty product made for fancy dress, drama and satire. {name if name!='Evil Epstein' else 'Jeffrey Epstein'} has not endorsed, sponsored or approved this product, and Foxy Printing has no connection with {pron}{' or ' + ('his' if pron=='him' else 'her') + ' estate' if estate else ''}. The name is used only to describe the design. Foxy Printing does not support or promote the views or actions of any person portrayed.</p>")
    a='an' if name[0] in 'AEIOU' or name.startswith('R ') else 'a'
    meta=f"{a.capitalize()} {name} face mask for {muses}. Printed in full colour on 350gsm card, cut to shape with eye holes and elastic."
    if len(meta)>155: meta=f"{a.capitalize()} {name} face mask for {muses}. Full-colour print on 350gsm card, cut to shape with eye holes and elastic."
    st=f"{SEONAME.get(name+role,name)} Face Mask {stail} | Foxy Printing"
    if len(st)>60: st=f"{name} Face Mask | Foxy Printing"
    return d,meta,st
