"""Bar mat designs found in Dropbox on 8 Oct 2026 that were not yet in the store.
Facts only from plan/product-facts.md "Home bar, garden bar & man cave" + the live bar-mat listings:
dye-sublimation printed, rubber-backed, sizes (owner 8 Oct 2026) Small 440mm x 250mm / Large 880mm x 250mm (corrected from 330mm by the owner, 8 Oct 2026).
Thickness, care and dispatch time are ASK, so the copy promises none of them.
"""

DB = "/Bar Runners Bar Mats"
GB_DIR = DB + "/CLUB MATS (GENERIC BADGE)"
X3_DIR = DB + "/bar mats 3x10"
OT_DIR = DB + "/others mats x10"
BR_DIR = "/!!!BRAD ARTWORK!!!!!/bar mats/NEW DESIGNS BM"
AN_DIR = "/Anna and RAFIA Work 2/Old Jobs/November 2021/BAR MATS"

P = []

# ---------------------------------------------------------------- A. club / team colour mats (generic badge)
GB = [
    # key, colour words, google colour, code, Dropbox file stem (440 / 880), hook, colour note, close
    ("red_white", "Red & White", "Red/White", "CBMRW", ("RED AND WHITE 440x250", "RED AND WHITE 880x250"),
     "Red and white has been on more football shirts than any other combination, so this one suits a lot of clubhouses.",
     "Bold red panels with white blocks either side and a white ring around each badge.",
     "Pair it with a set of pint glasses for the committee and the bar is ready for the new season."),
    ("red_white_stripes", "Red & White Stripes", "Red/White", "CBMRWS", ("RED AND WHITE STRIPES 440x250", "RED AND WHITE STRIPS 880x250"),
     "Striped shirts are a tradition at plenty of grassroots clubs, and this mat brings the stripes to the bar.",
     "Red background broken up by white stripe bars, with your badge framed in white at each end.",
     "A nice thank-you for the volunteers who keep the tea hut and the bar running every Saturday."),
    ("blue_white", "Blue & White", "Blue/White", "CBMBW", ("BLUE AND WHITE 440x250", "BLUE AND WHITE ]880x250"),
     "If your lot play in royal blue and white, this personalised blue and white club bar mat will look right at home behind the bar.",
     "Royal blue centre panel, crisp white end blocks and blue-ringed badge circles.",
     "Order a large one for the clubhouse and a small one for the chairman’s home bar."),
    ("blue_white_stripes", "Blue & White Stripes", "Blue/White", "CBMBWS", ("BLUE AND WHITE STRIPES 440x250", "BLUE AND WHITE STRIPES 880x250"),
     "Blue and white stripes say football club straight away, whether that’s a Sunday league side or a cricket club with a bar.",
     "Royal blue with white stripe bars running through it and your badge in a white ring at each end.",
     "It makes a great raffle prize at the end-of-season presentation night."),
    ("black_white_stripes", "Black & White Stripes", "Black/White", "CBMBKWS", ("BLACK AND WHITE STRIPES 440x250", "BLACK AND WHITE STRIPES 880x250"),
     "Black and white stripes never go out of fashion, and this personalised black and white striped bar mat keeps it classic.",
     "Black background with white stripe blocks, plus white-ringed circles for the badge.",
     "Add a matching small mat for the home bar of your most loyal supporter."),
    ("green_white", "Green & White", "Green/White", "CBMGW", ("GREEN AND WHITE 440x250", "GREEN AND WHITE 880x250"),
     "For clubs in green and white, from football and rugby to hockey and bowls, this mat gives the bar a proper team feel.",
     "Grass-green centre panel with white end blocks and green-ringed badge circles.",
     "A good gift for the groundsman who keeps the pitch looking as green as the mat."),
    ("green_white_stripes", "Green & White Hoops", "Green/White", "CBMGWS", ("GREEN AND WHITE STRIPES 440x250", "GREEN AND WHITE STRIPES 880x250"),
     "Green and white bands are a favourite for football and rugby sides, and this bar runner carries them across the whole bar.",
     "Green background with white bands, finished with your badge inside white rings.",
     "Lovely for a rugby club bar, alongside a few personalised pint glasses for the captains."),
    ("lightblue_white", "Sky Blue & White", "Blue/White", "CBMLBW", ("LIGHT BLUE AND WHITE 440x250", "LIGHT BLUE AND WHITE 880x250"),
     "Sky blue sides are often the friendliest clubs in the league, and this personalised sky blue club bar mat suits them perfectly.",
     "Soft sky-blue centre with white ends and sky-blue rings around the badge circles.",
     "Order one for the clubhouse and a small one as a birthday gift for a lifelong fan."),
    ("navy_white", "Navy & White", "Navy/White", "CBMNW", ("NAVY AND WHITE 440x250", "NAVY AND WHITE 880x250"),
     "Navy and white is smart and understated, which makes this one popular with golf, cricket and sailing clubs as well as football teams.",
     "White centre panel with deep navy ends and navy rings around each badge.",
     "It also suits a works social club or a darts team – anyone with a badge they are proud of."),
    ("black_orange", "Black & Orange", "Orange/Black", "CBMBO", ("BLACK AND ORANGE 440x250", "BLACK AND ORANGE 880x250"),
     "Orange and black teams always stand out, and this personalised orange and black club bar mat is just as hard to miss.",
     "Bright orange centre with black end blocks and orange rings around the badge circles.",
     "Great for a speedway, ice hockey or football supporters’ bar."),
    ("black_yellow", "Black & Yellow", "Black/Yellow", "CBMBKY", ("BLACK AND YELLOW 440x250", "BLACK AND YELLOW 880x250"),
     "Black and yellow is a proper wasps-and-hornets colour scheme, and this mat keeps the black front and centre.",
     "Black centre panel with yellow end blocks and yellow-ringed badge circles.",
     "Brilliant for a rugby or football club bar, with a few beer mats and pint glasses to finish the look."),
    ("yellow_black", "Yellow & Black", "Yellow/Black", "CBMYB", ("YELLOW AND BLACK 440x250", "YELLOW AND BLACK 880x250"),
     "This version flips the colours so bright yellow leads, ideal for teams whose home shirt is gold or amber.",
     "Golden-yellow centre with black end blocks and black-ringed badge circles.",
     "A cheerful gift for the team treasurer – or anyone who has washed the kit every week for years."),
    ("blue_yellow", "Blue & Yellow", "Blue/Yellow", "CBMBLY", ("BLUE AND YELLOW 440x250", "BLUE AND YELLOW 880x250"),
     "Blue and yellow is a bright, happy combination, and this personalised blue and yellow club bar mat brings it to the bar top.",
     "Royal blue centre with yellow end blocks and blue rings around each badge.",
     "Pick up a small mat too for the coach’s kitchen counter."),
    ("blue_red", "Blue & Red", "Blue/Red", "CBMBR", ("BLUE AND RED 440x250", "BLUE AND RED 880x250"),
     "Blue and red halves and stripes turn up at clubs all over the country, and this design gives them pride of place.",
     "Royal blue centre with red end blocks and stripes, with your badge in white rings.",
     "Lovely for an anniversary year – add the year your club was founded in the Est. box."),
    ("green_yellow", "Green & Yellow", "Green/Yellow", "CBMGY", ("GREEN AND YELLOW 440x250", "GREEN AND YELLOW 880x250"),
     "Green and gold teams don’t get many matching gifts, so this personalised green and yellow club bar mat fills the gap.",
     "Sunny yellow centre with green end blocks and green-ringed badge circles.",
     "Ideal for a cricket or bowls club with a busy bar on a summer evening."),
    ("yellow_red", "Yellow & Red", "Yellow/Red", "CBMYR", ("YELLOW AND RED 440x250", "YELLOW AND RED 880x250"),
     "Yellow and red is warm and loud, perfect for a club that likes to be heard on a match day.",
     "Golden-yellow centre with red end blocks and red rings around each badge.",
     "A great present for a club legend’s testimonial year or a 50th birthday at the clubhouse."),
    ("claret_blue", "Claret & Blue", "Burgundy/Blue", "CBMCB", ("CLARET AND BLUE 440x250", "CLARET AND BLUE 880x250"),
     "Claret and sky blue is a much-loved football combination, and this personalised claret and blue club bar mat is made for those clubs.",
     "Deep claret centre with sky-blue end blocks and claret rings around the badge circles.",
     "Pair it with a claret and blue scarf for the fan who has everything."),
]
for i, (key, cw, gcol, code, files, hook, colour_note, close) in enumerate(GB):
    cl = cw.lower().replace("&", "and")
    P.append(dict(
        key=f"gb_{key}", group="GB", code=code, design=f"{cw} Club",
        title=f"Personalised Club Bar Mat Runner – {cw} Team Colours – Your Club Badge & Name",
        handle=f"personalised-club-bar-mat-{cl.replace(' ', '-')}",
        primary=f"personalised {cl} club bar mat",
        seo_title=f"Personalised {cw} Club Bar Mat | Foxy Printing",
        colour=gcol, price=("9.99", "13.99"),
        fields=["Club or team name", "Club badge upload", "Welcome line (optional)", "Est. year (optional)"],
        hook=hook, colour_note=colour_note, close=close,
        extra_tags=["Football Bar Mats", "Personalised Bar Mat", "club bar mat", "team colours", "clubhouse", "football club gift", "io-bar-mats"],
        dropbox=[f"{GB_DIR}/{files[0]}.pdf", f"{GB_DIR}/{files[1]}.pdf"],
        channels="all"))

# ---------------------------------------------------------------- B. "bar name" designs (bar mats 3x10, 21-30)
X3 = [
    (21, "Blush Script", "Mauve", "PBM21", "personalised script name bar runner",
     "A soft mauve runner with a gold handwritten name framed by fine swirls, and WELCOME either side.",
     ["Name or bar name"],
     "Their name is written in flowing gold script in the centre frame; on the small mat the name sits on its own in the frame.",
     "Soft mauve and gold suit a gin corner or a living-room drinks trolley as much as a pub-style bar",
     "Wrap it up with a bottle of their favourite gin for a birthday or housewarming."),
    (22, "Emerald Flourish", "Green", "PBM22", "personalised green and gold bar runner",
     "Deep emerald green with gold scrollwork and the bar name in an elegant hand-lettered style.",
     ["Bar name"],
     "Type the bar name and we set it in gold script inside the scrolled border, sized to fit.",
     "Emerald and gold give a garden bar or a dark-wood home bar a classic, old-hotel feel",
     "It looks lovely next to a set of personalised whisky tumblers."),
    (23, "Crown & Copper", "Teal", "PBM23", "personalised teal bar mat with crown",
     "Spaced-out capitals in copper on a teal panel, with a little crown and filigree above and below.",
     ["Bar name"],
     "The bar name runs across the middle in wide copper capitals, so short names of one or two words look best.",
     "The copper border and crown give it a proper ‘the King’s Arms’ look for a home pub",
     "Ideal for a new home bar, with a matching sign for the door."),
    (24, "Plum Filigree", "Purple", "PBM24", "personalised purple bar runner",
     "Rich plum purple with lilac filigree and the bar name in tall, elegant capitals.",
     ["Bar name"],
     "Your bar name sits in large lilac lettering in the middle, with filigree trims top and bottom.",
     "A rich purple that stands out against a white kitchen island or a grey garden bar",
     "A thoughtful gift for a Mum who has just built her own cocktail corner."),
    (25, "Teal Welcome", "Teal", "PBM25", "personalised welcome bar mat",
     "Dark teal with a soft ivy pattern, the bar name in white capitals and WELCOME above and below.",
     ["Bar name"],
     "The bar name goes in the middle line; the WELCOME lines and ivy trim are part of the design.",
     "The welcome lines make it a friendly first thing guests see when they walk up to the bar",
     "Pair it with a personalised bar sign so the whole corner matches."),
    (26, "Walnut & Gold", "Brown", "PBM26", "personalised wood effect bar runner",
     "A dark walnut wood-effect print with ornate gold corners and the bar name in gold capitals.",
     ["Bar name"],
     "We print the bar name in gold between the curved gold flourishes, on a printed wood-grain background.",
     "The wood-effect print blends in with a traditional pub-style bar or a log-cabin garden bar",
     "A great gift for Dad’s shed bar alongside a couple of personalised pint glasses."),
    (27, "Olive Oval", "Green", "PBM27", "personalised bar runner with est year",
     "Olive green with a gold oval frame, WELCOME across the top and an EST. year underneath the bar name.",
     ["Bar name", "Est. year (optional)"],
     "Add the bar name and the year it opened (or the year you moved in) and both are printed inside the gold oval.",
     "The established year turns it into a keepsake for a new home or a milestone anniversary",
     "Lovely as a housewarming gift with the year they got the keys."),
    (28, "Rustic Established", "Brown", "PBM28", "personalised established bar mat",
     "A rustic wood-effect panel with a royal blue border, WELCOME TO at the top and ESTABLISHED with your year at the bottom.",
     ["Bar name", "Est. year (optional)"],
     "Your bar name is printed big in the middle, with your own year in the ESTABLISHED line underneath.",
     "The blue frame and wood print give it a heritage brewery look",
     "Add a matching personalised beer stein for the full pub feel."),
    (29, "Rainbow Bubbles", "Multicolor", "PBM29", "personalised colourful bar name mat",
     "Each letter of the bar name sits in its own coloured circle on a dark olive background, with WELCOME spaced along the top and bottom.",
     ["Bar name (short names work best)"],
     "Every letter gets its own bright bubble, so shorter names and nicknames look best – think PUB, TOMS or THE DEN.",
     "Bright, playful colours that work in a games room or a summer garden bar",
     "A fun gift for a 30th or 40th birthday party at home."),
    (30, "Ruby Script", "Red", "PBM30", "personalised red bar runner",
     "Ruby red with a fine filigree frame, the bar name in flowing script and ‘enjoy your time’ in small capitals.",
     ["Bar name"],
     "Your bar name is written across the middle in a flowing script, set inside the filigree frame.",
     "Deep red brings warmth to a dark bar, especially by candlelight on a winter evening",
     "Perfect for a Valentine’s or anniversary gift for a couple who love hosting."),
]
for n, design, gcol, code, primary, look, fields, how, b1, close in X3:
    P.append(dict(
        key=f"x3_{n}", group="X3", code=code, design=design,
        title=f"Personalised Bar Mat Runner – {design} Design – Your Bar Name",
        handle=f"personalised-bar-mat-runner-{design.lower().replace(' & ', '-').replace(' ', '-')}",
        primary=primary, seo_title=None, colour=gcol, price=("12.99", "16.99"),
        fields=fields, look=look, how=how, b1=b1, close=close,
        extra_tags=["Personalised Bar Mat", "bar name", "home bar gift", "io-bar-mats"],
        dropbox=[f"{X3_DIR}/{n}. 440x250.pdf", f"{X3_DIR}/{n}. 880x250.pdf"],
        img=("x3", n), channels="all"))

# ---------------------------------------------------------------- C. others mats x10
OT = [
    (1, "My Cave My Rules Navy", "Navy", "BMO01", "my cave my rules bar mat", False,
     "MY CAVE MY RULES in bold gold capitals on royal navy, with an ornate gold crown border.", None,
     "The gold crown border gives it a regal, tongue-in-cheek feel for the king of the man cave",
     "Pair it with a ‘man cave’ sign for the door."),
    (2, "Well Come In Bud", "Brown", "BMO02", "funny beer bar mat", False,
     "A warm brown runner with hand-drawn frothy pints and the pun WELL. COME IN BUD! in the middle.", None,
     "A little pun that gets a smile from every guest who leans on the bar",
     "A cheeky stocking filler for the beer lover in the family."),
    (3, "Man Cave Welcome", "Grey", "BMO03", "man cave bar runner", False,
     "MAN CAVE in wide cream capitals on charcoal, with WELCOME lines and gold hazard-style stripes top and bottom.", None,
     "The charcoal and gold stripes look sharp in a garage bar or a gaming den",
     "Add a set of man cave coasters for the full look."),
    (4, "Name Medallions", "Navy", "BMO04", "personalised name bar mat", True,
     "Each letter of the name sits in its own red ornamental medallion on deep navy, framed with fine lines.", ["Name (short names work best)"],
     "Medallion letters make even a short name look grand – ideal for a first name or nickname",
     "A great 18th or 21st birthday present for their first home bar."),
    (5, "Man Cave Take a Sip", "Black", "BMO05", "man cave whisky bar mat", False,
     "MAN CAVE in gold inside a laurel wreath, with splashing whisky glasses and TAKE A SIP AND ENJOY either side.", None,
     "Splashing whisky glasses and a gold laurel give it a smart cocktail-lounge look",
     "Wrap it with a pair of whisky tumblers for Father’s Day."),
    (6, "My Cave My Rules Whiskey", "Orange", "BMO06", "my cave my rules whiskey bar mat", False,
     "MY CAVE MY RULES in big black letters on bright orange, with a whiskey bottle in the middle.", None,
     "Bright orange and black make it the loudest thing on the bar",
     "A bold gift for a whiskey drinker’s garage bar."),
    (7, "Burgundy Welcome", "Burgundy", "BMO07", "personalised welcome name bar runner", True,
     "Burgundy with a fine scrolled frame, the name in a light script and WELCOME at each end.", ["Name or bar name"],
     "A softer, more elegant look that suits a dining room drinks cabinet",
     "Lovely for a wedding or anniversary present with their surname."),
    (8, "Enjoy My Man Cave", "Turquoise", "BMO08", "enjoy my man cave bar mat", False,
     "ENJOY MY MAN CAVE in dark and white capitals on turquoise, with a playful scatter of coloured dots.", None,
     "Bright turquoise makes a change from the usual black and brown man cave colours",
     "Pick up a small one too for the shed."),
    (9, "Man Cave Slate", "Blue", "BMO09", "slate blue man cave bar runner", False,
     "MAN CAVE in large white capitals on slate blue, with gold WELCOME ribbons either side.", None,
     "A calm slate blue that sits nicely in a modern grey or white home bar",
     "A neat Christmas present for the man cave owner who is impossible to buy for."),
    (10, "Golden Lions", "Red", "BMO10", "personalised lion bar runner", True,
     "Two rampant golden lions on bright red with a little crown, framing your own wording in gold capitals.", ["Your text (bar name or message)"],
     "The golden lions give it a proud, heraldic look – great for an England fan’s bar",
     "A brilliant gift for the big tournament summer, with a few pint glasses."),
]
for n, design, gcol, code, primary, pers, look, fields, b1, close in OT:
    P.append(dict(
        key=f"ot_{n}", group="OT", code=code, design=design,
        title=(f"Personalised Bar Mat Runner – {design} Design" + (" – Your Name" if pers else "")) if pers
              else f"{design} Bar Mat Runner – Home Bar & Man Cave Gift",
        handle=("personalised-bar-mat-runner-" if pers else "bar-mat-runner-") + design.lower().replace(" ", "-"),
        primary=primary, colour=gcol, price=("12.99", "16.99"),
        fields=fields or [], look=look, b1=b1, close=close, personalised=pers,
        extra_tags=(["Personalised Bar Mat"] if pers else []) + ["man cave", "home bar gift", "io-bar-mats"],
        dropbox=[f"{OT_DIR}/{n}. 440x250 others.pdf", f"{OT_DIR}/{n}. 880x250 others.pdf"],
        img=("ot", n), channels="web" if n == 6 else "all",
        brand="Jack Daniel’s" if n == 6 else None))

# ---------------------------------------------------------------- D. Brad's new designs
BR = [
    ("best_bar", "Best Bar in Town", "Black", "BMBBT", "personalised best bar in town bar mat",
     "A black runner with a red ribbon banner for your name, BAR underneath and ‘Probably the best bar in town’ in script.",
     ["Name (on the red ribbon)"], "WELCOME TO THE BEST BAR IN TOWN"),
    ("gin_pink", "Gin Bar Pink", "Pink", "BMBGIN", "personalised gin bar mat",
     "Black with a pink neon-style border, the name in pink script above GIN, B-A-R in pink tiles and LET THE FUN BE GIN.",
     ["Name (e.g. Anna’s)"], "LET THE FUN BE GIN PINK"),
    ("man_cave", "Name Man Cave", "Black", "BMBMC", "personalised man cave bar mat",
     "Black and white with big ornate scrolls above and below, and ANY NAME MAN CAVE in classic capitals.",
     ["Name"], "MAN CAVE"),
    ("neon_cocktail", "Neon Cocktail Menu", "Black", "BMBNEON", "personalised neon cocktail bar mat",
     "A black runner with a glowing neon cocktail glass, your name in pink neon script and a row of classic cocktail names along the top and bottom.",
     ["Name or bar name"], "NEON COCKTAIL BAR"),
    ("union_jack", "Distressed Union Jack", "Multicolor", "BMBUJ", "personalised union jack bar mat",
     "A worn, vintage-style Union Jack with a white plaque in the middle for your bar name.",
     ["Bar name"], "UNION JACK BAR MAT"),
    ("vintage_black", "Vintage Black Established", "Black", "BMBVB", "personalised established bar mat black",
     "Black with white Victorian corner flourishes, WELCOME TO, the bar name in a serif face and ‘Established’ with your year.",
     ["Bar name", "Est. year (optional)"], "VINTAGE BLACK DESIGN"),
    ("vintage_wood", "Vintage Wood Established", "Brown", "BMBVW", "personalised wooden bar mat",
     "A printed oak-plank background with carved-style scrolls, WELCOME TO, the bar name in large serif capitals and EST. with your year.",
     ["Bar name", "Est. year (optional)"], "VINTAGE TEXT WOODEN BACKGROUND"),
]
for key, design, gcol, code, primary, look, fields, stem in BR:
    big = None if key == "vintage_wood" else (f"{BR_DIR}/UNION JACK BIGGER DESIGN.pdf" if key == "union_jack" else f"{BR_DIR}/{stem} BIGGER DESIGN.pdf")
    P.append(dict(
        key=f"br_{key}", group="BR", code=code, design=design,
        title=f"Personalised Bar Mat Runner – {design} Design – Your Name",
        handle=f"personalised-bar-mat-runner-{design.lower().replace(' ', '-')}",
        primary=primary, colour=gcol, price=("12.99", "16.99"), fields=fields, look=look,
        extra_tags=["Personalised Bar Mat", "home bar gift", "io-bar-mats"],
        dropbox=[f"{BR_DIR}/{stem}.pdf"] + ([big] if big else []),
        img=("br", key), channels="web" if key == "neon_cocktail" else "all"))

# ---------------------------------------------------------------- E. Anna's designs (Nov 2021 batch, finished ones only)
AN = [
    (1, "Beer Splash Welcome", "Black", "BMA01", "personalised beer bar mat", True,
     "Black with a big hand-lettered ‘Beer’ splashing out of two frothy tankards, and WELCOME TO with your bar name in gold.", ["Bar name"]),
    (2, "Life is Brewtiful", "Black", "BMA02", "life is brewtiful bar mat", False,
     "A vintage fist raising a frothy tankard and LIFE IS BREWTIFUL in chunky red lettering on charcoal.", None),
    (3, "Cheers Welcome", "Green", "BMA03", "personalised cheers bar mat", True,
     "Two hands clinking pints on a bright green background, with EST. year and WELCOME TO your bar name in the centre.", ["Bar name", "Est. year (optional)"]),
    (4, "Beer O’Clock Bottles", "Orange", "BMA04", "beer o’clock bar mat", False,
     "A pattern of beer bottles and glasses on burnt orange, with BEER O’CLOCK in an orange script panel.", None),
    (5, "Cocktail Welcome", "Brown", "BMA05", "personalised cocktail bar mat", True,
     "Watercolour cocktails – a mojito, a gin and tonic and a pink fizz – with ‘Welcome to’, your name and EST. year.", ["Name or bar name", "Est. year (optional)"]),
    (8, "Best Bar Cream", "Cream", "BMA08", "personalised cream bar runner", True,
     "Cream with curling parchment scrolls at each end, ‘Welcome to the Best Bar of the Town’ and a ribbon for your bar name and year.", ["Bar name", "Est. year (optional)"]),
    (10, "Vintage Diamond", "Grey", "BMA10", "personalised vintage bar runner", True,
     "A distressed grey background with a vintage diamond label in the middle holding your bar name and year.", ["Bar name", "Est. year (optional)"]),
    (12, "It’s Beer O’Clock", "Beige", "BMA12", "it’s beer o’clock bar runner", False,
     "Two engraved-style hands raising glasses on aged parchment, with IT’S BEER O’CLOCK in the middle.", None),
    (13, "Welcome Woodgrain", "Brown", "BMA13", "personalised wood effect welcome bar mat", True,
     "Dark wood-grain with gold scroll trims, WELCOME TO, your wording in big gold capitals and an ESTABLISHED line.", ["Your wording", "Established date (optional)"]),
    (14, "Art Deco Ticket", "Bronze", "BMA14", "personalised art deco bar runner", True,
     "A bronze and black art deco ticket frame with WELCOME, your name in deco capitals and EST. year.", ["Name or bar name", "Est. year (optional)"]),
]
for n, design, gcol, code, primary, pers, look, fields in AN:
    t = design.replace("’", "'")
    P.append(dict(
        key=f"an_{n}", group="AN", code=code, design=design,
        title=(f"Personalised Bar Mat Runner – {design} Design – Your Bar Name" if pers
               else f"{design} Bar Mat Runner – Home Bar & Pub Gift"),
        handle=("personalised-bar-mat-runner-" if pers else "bar-mat-runner-") + t.lower().replace("'", "").replace(" ", "-"),
        primary=primary, colour=gcol, price=("12.99", "16.99"), fields=fields or [], look=look, personalised=pers,
        extra_tags=(["Personalised Bar Mat"] if pers else []) + ["home bar gift", "io-bar-mats"],
        dropbox=[f"{AN_DIR}/{n}  - 880.pdf"] + ([f"{AN_DIR}/{n}  - 440.pdf"] if n <= 7 else []),
        img=("an", n), channels="all"))

for p in P:
    p.setdefault("personalised", bool(p.get("fields")))
