"""Per-design facts for the bar-mat copy refresh (8 Oct 2026, owner: "give all the bar mats new better
seo descriptions and check all metatags and google data").

Looks below were written from each listing's own main image (checked 8 Oct 2026). Example names in the
mock-ups (Dave's Bar, Edward's Pub...) are only examples - the customer's own wording replaces them.
Facts allowed (plan/product-facts.md, Home bar sheet): Small 440mm x 250mm, Large 880mm x 250mm,
rubber-backed, dye-sublimation printed, dishwasher safe. Rubber thickness is ASK - never stated.
"""

# Milan M-series (51 listings, M1-M50 + a duplicate M49). Fields:
# n, pk (primary keyword), seo (keyword for SEO title, no trademarks), look, hook, close, google colour, example?
M = {
    1: ("personalised cheers beer bar mat", "Personalised Cheers Beer Bar Mat",
        "A warm orange-to-red glow with two frothy pints clinking at either end, and your pub name in bold old-English lettering between COME EARLY and STAY LATE.",
        "It’s the one for the friend who always says ‘just one more’ and means it.",
        "Pick it up for a 40th, or for whoever has just finished building the shed bar.", "Orange", "James’s Pub"),
    2: ("personalised art deco bar mat", "Personalised Art Deco Bar Mat Runner",
        "A navy runner covered in a fine art deco grid, with WELCOME TO, your bar name in spaced-out capitals and an EST. year.",
        "Smart enough for a dining-room drinks cabinet, but still says ‘this is my bar’.",
        "Lovely as a housewarming present with the year they moved in.", "Navy", "Donald’s Bar"),
    3: ("personalised black pub bar mat", "Personalised Black Pub Bar Mat Runner",
        "Clean and simple: black, with double white rules, WELCOME TO at the top, your pub name in tall white capitals and the year underneath.",
        "If you like things understated, this is the classic one.",
        "Pair it with a set of personalised pint glasses for a proper pub feel at home.", "Black", "Matthew’s Pub"),
    4: ("personalised come early stay late bar mat", "Personalised Come Early Stay Late Bar Mat",
        "Deep navy with gold lettering, two overflowing tankards and the old landlord’s promise: COME EARLY, your pub name, STAY LATE.",
        "A cheeky nod to the host whose ‘quick drink’ always turns into a long night.",
        "Great for Father’s Day, wrapped up with a couple of his favourite ales.", "Navy", "Paul’s Pub"),
    5: ("personalised welcome pub bar mat", "Personalised Welcome Pub Bar Mat Runner",
        "Teal with a cream arch banner reading WELCOME TO THE, your pub name in chunky cream capitals and WE SERVE THE BEST underneath.",
        "It gives a garden bar or a garage conversion the look of a proper country inn.",
        "A brilliant retirement present for someone finally opening their own ‘local’ at home.", "Teal", "Travellers Rest"),
    6: ("personalised established bar mat in black", "Personalised Established Bar Mat – Black",
        "Black with a curved WELCOME TO, your bar name in crisp white capitals and a small EST. ribbon for the year.",
        "Black goes with everything, from a chrome kitchen island to a dark-wood pub bar.",
        "It’s also made in red, green and blue if you want to match your bar.", "Black", "Dave’s Bar"),
    7: ("personalised established bar mat in red", "Personalised Established Bar Mat – Red",
        "The same classic established layout in deep pub red: WELCOME TO, your bar name in white capitals and a cream EST. ribbon.",
        "Red brings a cosy, traditional-pub warmth, especially with a bit of low lighting.",
        "Add a matching sign above the bar and the whole corner ties together.", "Red", "Dave’s Bar"),
    8: ("personalised established bar mat in green", "Personalised Established Bar Mat – Green",
        "Bottle green with a curved WELCOME TO, your bar name in white capitals and a cream ribbon with the year you opened.",
        "Green and cream has that old snug-bar look that suits wood panelling and brass.",
        "A thoughtful gift for a golfer or a gin lover with a garden bar.", "Green", "Dave’s Bar"),
    9: ("personalised established bar mat in blue", "Personalised Established Bar Mat – Blue",
        "A distressed navy blue background with WELCOME TO arched over the top, your bar name in huge white capitals and a tan EST. ribbon.",
        "The worn, vintage texture makes a brand-new home bar feel like it has been open for years.",
        "Order the large runner for the bar and the small one for the drinks trolley.", "Blue", "Dave’s Bar"),
    10: ("personalised whisky bar mat", "Personalised Whisky Bar Mat Runner",
        "Dark and moody, with splashing whisky tumblers at each end, Welcome to in script and your bar name in gold capitals.",
        "Made for the whisky drinker who has a favourite chair, a favourite glass and now their own bar mat.",
        "Wrap it with a pair of tumblers and a bottle for a milestone birthday.", "Black", "Mathew’s Bar"),
    11: ("personalised family bar mat", "Personalised Family Bar Mat Runner",
        "Simple black with your wording in a flowing white handwritten script, such as ‘The Jackson Family Bar’.",
        "Lovely when the bar belongs to the whole household rather than just one person.",
        "A warm wedding or anniversary present with the couple’s new surname.", "Black", "The Jackson Family Bar"),
    12: ("personalised gin bar mat", "Personalised Gin Bar Mat Runner",
        "Black with a crisp white diamond label in the middle, holding your bar name and a little crest of glasses.",
        "The label style looks like the front of a craft gin bottle, so it’s spot on for a gin corner.",
        "Put it under a row of copa glasses and a couple of tonics and you have a gin bar.", "Black", "Paul’s Bar"),
    13: ("personalised wine bar mat", "Personalised Wine Bar Mat Runner",
        "Black with a red wine-ring stain, a script It’s Always above your bar name and Wine O’Clock beneath.",
        "For anyone whose idea of a bar is a good bottle of red and nowhere to be in the morning.",
        "A fun birthday present for a wine lover, with a bottle tucked in the parcel.", "Black", "Fine Harvest"),
    14: ("personalised beer o’clock bar mat", "Personalised Beer O’Clock Bar Mat Runner",
        "Mustard yellow with hop sprigs in each corner, IT’S ALWAYS at the top, your bar name in big black capitals and BEER O’CLOCK underneath.",
        "Made for real-ale fans and home brewers, the hops say it all.",
        "Pair it with a personalised beer stein for the home brewer in the family.", "Yellow", "Billy’s Bar"),
    15: ("personalised whiskey glass bar mat", "Personalised Whiskey Glass Bar Mat",
        "Black with glowing amber whiskey glasses at each end and your bar name in big white capitals across the middle.",
        "A great match for a dark bar with a shelf of bottles behind it.",
        "Nice for a 50th or 60th, with a whiskey tasting set to go with it.", "Black", "Bobby’s Bar"),
    16: ("personalised rum bar mat", "Personalised Rum Bar Mat Runner",
        "Black with your bar name in chunky gold lettering, RUM BAR spaced out underneath and two tumblers of rum on the rocks.",
        "For the rum fan who keeps more bottles than they will admit to.",
        "Wrap it with a bottle of spiced rum for a birthday they won’t forget.", "Black", "Crown"),
    17: ("old fashioned cocktail bar mat", "Old Fashioned Cocktail Bar Mat Runner",
        "Black with Call me OLD FASHIONED in warm orange lettering and a short tumbler of the classic cocktail at each end.",
        "A gentle joke for the cocktail fan who likes things done the proper way.",
        "Add a set of rocks glasses and it’s a ready-made gift for a cocktail lover.", "Black", None),
    18: ("personalised monogram pub bar mat", "Personalised Monogram Pub Bar Mat Runner",
        "Navy with a bold orange stripe, a round badge holding your initial and EST. year, and WELCOME TO with your pub name either side.",
        "The monogram badge looks like a brewery logo, so it suits a home pub with a proper name.",
        "A great gift for a new homeowner, with their initial on the badge.", "Navy", "Brian’s Pub (initial B)"),
    19: ("personalised tiki bar mat", "Personalised Tiki Bar Mat Runner",
        "Sky blue with palm trees and carved tiki faces, your bar name in a red script and EAT. DRINK. CHILL. along the bottom.",
        "Instant holiday feeling for a garden bar, a hot tub corner or a summer party.",
        "Pair it with a cocktail set and you’re ready for the first barbecue of the summer.", "Light Blue", "Aloha Bar"),
    20: ("personalised union jack bar mat", "Personalised Union Jack Bar Mat Runner",
        "A bold Union Jack with a navy panel in the middle for your bar name, plus a red EST. tab and year.",
        "Perfect for a proper British pub at home, a royal celebration or a big match day.",
        "Brilliant for a street party or a garden bar flying the flag.", "Multicolor", "Richard’s Bar"),
    21: ("personalised liqueur bar mat", "Personalised Liqueur Bar Mat Runner",
        "Black with your bar name in gold capitals over a colourful line-up of bottles, and MAKE YOUR CHOICE at each end.",
        "The row of bottles looks like a well-stocked back bar, even before you have bought them all.",
        "A good one for a cocktail party host or someone just starting their bottle collection.", "Black", "The Greyhound Bar"),
    22: ("skull and crown bar mat", "Skull and Crown Bar Mat Runner",
        "A burnt orange runner with a row of skulls wearing gold crowns, framed in black.",
        "Bold, a little bit rock and roll, and a good match for a biker’s garage or a tattoo-lover’s den.",
        "Pick it up as a gift for the rocker in the family.", "Orange", None),
    23: ("personalised whiskey bar mat", "Personalised Whiskey Bar Mat Runner",
        "Black with gold stars and a wavy, hand-lettered WHISKEY BAR in cream and gold, with your name above and EST. year below.",
        "It has a touch of the old saloon about it, which suits a wooden bar and a bottle of bourbon.",
        "Wrap it with a whiskey stone set for a memorable Father’s Day.", "Black", "Billy’s"),
    24: ("bar rules bar mat", "Funny Bar Rules Bar Mat Runner",
        "Black with bold orange lettering and the two golden rules of every bar: Rule 1, the bartender is always right; Rule 2, if the bartender is wrong, see Rule 1.",
        "It settles every argument at the bar before it starts.",
        "A funny gift for the person who always ends up pouring the drinks.", "Black", None),
    25: ("personalised irish pub bar mat", "Personalised Irish Pub Bar Mat Runner",
        "Bright green with shamrocks, two frothy green pints and Irish Pub above your pub name and EST. year.",
        "Made for St Patrick’s Day, but it’ll make every night at the bar feel like a session.",
        "Order it ahead of 17 March and the party sorts itself out.", "Green", "Three Horseshoes"),
    26: ("personalised gin bar runner", "Personalised Etched Gin Bar Runner",
        "Dark green with fine etched-style drawings of gin glasses and citrus, WELCOME TO THE above your name and GIN BAR beneath.",
        "The etched drawings give it a vintage botanical look that gin fans love.",
        "Pair it with a balloon glass set for a gin lover’s birthday.", "Dark Green", "Victoria"),
    27: ("take one shot bar mat", "Take One Shot Bar Mat Runner",
        "A deep red to gold glow with TAKE ONE SHOT in big white letters and a shot glass for the O.",
        "Made for parties, birthdays and anyone who keeps a bottle of something in the freezer.",
        "Brilliant for an 18th or 21st with a set of shot glasses.", "Red", None),
    28: ("personalised cocktail bar mat", "Personalised Neon Cocktail Bar Mat Runner",
        "A purple brick wall with neon-style lettering, martini glasses at each end and WELCOME TO above your name.",
        "It brings the glow of a city cocktail bar to a kitchen island or a garden bar.",
        "Nice for a hen party host or a cocktail-loving friend.", "Purple", "Amelia’s"),
    29: ("personalised wine bar runner", "Personalised Red Wine Bar Runner",
        "Black with red wine splashing from glasses at each end, WELCOME TO in red and your name in big white capitals over WINE BAR.",
        "Wine lovers will appreciate a bar mat that catches the drips from a heavy pour.",
        "A good present for a couple’s anniversary with a bottle of red.", "Black", "Black Rose"),
    30: ("personalised wine o’clock bar mat", "Personalised Wine Ring Bar Mat Runner",
        "Black with a scatter of red wine rings, WELCOME TO at the top and your name in a flowing white script over WINE BAR.",
        "The wine rings are printed on, so the only real ones are the ones you wipe off.",
        "A cheeky gift for the friend who never uses a coaster.", "Black", None),
    31: ("personalised darts pub bar mat", "Personalised Darts Pub Bar Mat Runner",
        "Bright red with darts flying in from every side, WELCOME TO and your pub name in white capitals with an EST. year.",
        "For the darts player whose home bar has an oche marked out on the floor.",
        "Pair it with a set of personalised darts flights or a pint glass for the darts team captain.", "Red", "Edward’s Pub"),
    32: ("personalised bullseye bar mat", "Personalised Bullseye Bar Mat Runner",
        "Red and white target rings stretching the full length, a pub roundel with your initials in the bullseye and your pub name and year at each end.",
        "Bold enough to be seen from the other side of the room, which is handy in a games room.",
        "A great gift for a darts league player or a pub quiz team.", "Red", "Cross Keys"),
    33: ("personalised dartboard bar mat", "Personalised Dartboard Bar Mat Runner",
        "A grey brick-wall background with a dartboard at each end, WELCOME TO in gold and your pub name in big white capitals.",
        "Ideal for the games room where the dartboard is never left alone.",
        "Order the large runner for the bar and pop a small one by the oche.", "Grey", "Kings Head"),
    34: ("personalised pool bar mat", "Personalised Pool Ball Bar Mat Runner",
        "Green baize with cues along the edges and your pub name spelled out on numbered pool balls under WELCOME TO.",
        "Every letter sits on its own pool ball, so short names look best.",
        "A great gift for the pool player who has the table at home.", "Green", "Green Pub"),
    35: ("personalised snooker bar mat", "Personalised Snooker Bar Mat Runner",
        "Snooker-table green with a triangle of red balls at each end, WELCOME TO and your pub name in white.",
        "Spot on for a snooker room or a bar that sits beside the table.",
        "Lovely for a snooker fan watching the big tournaments at home.", "Green", "Windmill Pub"),
    36: ("personalised billiards bar mat", "Personalised Billiards Table Bar Mat Runner",
        "Green baize with coloured pool balls rolling across it, WELCOME TO THE above your pub name and EST. year.",
        "It looks like a tiny pool table on the bar, which always gets a smile.",
        "Pair it with a set of pint glasses for the pool team.", "Green", "Star Pub"),
    37: ("personalised dartboard runner", "Personalised Dartboard Sunburst Bar Mat",
        "A cream and black dartboard sunburst with darts in the bull, your pub name either side and the year round the middle.",
        "A cleaner, more graphic take on the darts theme for a modern games room.",
        "A good choice for a darts fan’s birthday with a set of flights.", "Cream", "The Anchor"),
    38: ("personalised fruit machine bar mat", "Personalised Fruit Machine Bar Mat Runner",
        "Orange and gold like the front of an old fruit machine, with your name in black capitals and spinning reels of cherries, plums and BAR symbols.",
        "A fun retro nod to the seaside arcade and the pub fruit machine.",
        "Brilliant for a games room or a Las Vegas themed birthday party.", "Orange", "Edward’s"),
    39: ("personalised retro pixel bar mat", "Personalised Retro Pixel Bar Mat Runner",
        "Purple scan-lines like an old arcade screen, pixel-style WELCOME TO and your pub name, and a PRESS FOR MORE BEER button underneath.",
        "Made for gamers who grew up feeding coins into arcade machines.",
        "A fun gift for a gamer’s den, alongside a retro gaming poster.", "Purple", "a well-known film name"),
    40: ("personalised arcade bar mat", "Personalised Arcade Bar Mat Runner",
        "A dark starry background with little pixel space invaders, your pub name in an arcade-style box and 1 BEER, 2 BEER where the player scores would be.",
        "Perfect for a retro gaming room with a console or two under the telly.",
        "A good birthday present for anyone who still knows their high score.", "Navy", "Arcade Pub"),
    41: ("personalised 8-bit bar runner", "Personalised 8-Bit Retro Gaming Bar Runner",
        "A sky-blue 8-bit platform game scene with pixel characters, ENJOY YOUR TIME AT above your pub name, and BEERS and HOURS counters in the corners.",
        "Made for anyone who spent their childhood jumping on pixel mushrooms.",
        "A nostalgic gift for a gamer’s birthday or a games room makeover.", "Light Blue", "a famous plumber’s name"),
    42: ("five more minutes gaming bar mat", "Five More Minutes Gaming Bar Mat Runner",
        "Bright purple and yellow stripes with a gamepad and an arcade joystick, and just five more MINUTES in neon-style lettering.",
        "Every gamer has said it, and every partner has heard it.",
        "A funny gift for a gamer’s den or a teenager’s first flat.", "Purple", None),
    43: ("gamer bar mat", "Let’s Have Some Fun Gamer Bar Mat Runner",
        "Deep navy with a white and red games controller at each end and LET’S HAVE SOME FUN in white and red.",
        "Made for a gaming room where the drinks sit next to the controllers.",
        "Pair it with a gamer’s mug for a birthday that hits the spot.", "Navy", None),
    44: ("personalised lime green bar mat", "Personalised Lime Green Cocktail Bar Mat",
        "Lime green with hand-sketched cocktail glasses and citrus, WELCOME TO and your pub name in big dark green lettering.",
        "Fresh and summery, it suits a garden bar or a light, bright kitchen.",
        "Order a pair for the patio bar and the kitchen.", "Green", "Edward’s Pub"),
    45: ("personalised beach bar mat", "Personalised Tropical Beach Bar Mat Runner",
        "A sunny beach scene with blue sky, palm leaves and tall red cocktails, WELCOME TO THE above your pub name and EST. year.",
        "Bring the beach bar home, whatever the British weather is doing.",
        "Lovely for a summer birthday or a hot tub party.", "Multicolor", "Cocktail Pub"),
    46: ("personalised jackpot bar mat", "Personalised Jackpot 777 Bar Mat Runner",
        "Bright yellow with a fruit-machine 777 jackpot in the middle and your bar name with Let’s roll! at each end.",
        "Loud, cheerful and made for a casino night or a games room.",
        "A great gift for a poker night host with a deck of cards.", "Yellow", "Exotic Bar"),
    47: ("personalised shots bar mat", "Personalised Shooters Bar Mat Runner",
        "Navy with golden shot glasses at each end, WELCOME TO THE above your bar name in white, slanted capitals.",
        "For the friend who always gets a round of shots in.",
        "Brilliant for a 21st or a stag do warm-up at home.", "Navy", "Shooter’s Bar"),
    48: ("personalised vintage wine bar mat", "Personalised Vintage Wine Bar Mat Runner",
        "A soft beige, grainy background with red wine glasses at each end and your bar name in a flowing wine-red script with the year.",
        "Warm and vintage, it suits a farmhouse kitchen or a cosy snug.",
        "A nice gift for a wine club host or a couple’s anniversary.", "Beige", "Mystery Bar"),
    49: ("satur-yay bar mat", "Satur-Yay Pink Cocktail Bar Mat Runner",
        "Soft pink with watercolour pink cocktails at each end and It’s Satur-yay! in a deep pink script.",
        "Made for the weekend, and for anyone whose favourite word is Saturday.",
        "Perfect for a hen party, a girls’ night in or a pink gin lover.", "Pink", None),
    50: ("personalised fruit cocktail bar mat", "Personalised Fruit Cocktail Bar Mat Runner",
        "Charcoal grey with sketched strawberries and red fruit cocktails, WELCOME TO THE above your pub name and the year.",
        "A fresh, fruity design for a summer cocktail bar.",
        "Nice for a garden party host with a jug of Pimm’s on the go.", "Black", "Coconut Pub"),
}

# M-series listings whose photos show branded whisky bottles as props (every M listing except M1, M9 and the
# image-less duplicate M49 7680139559163).
M_PROP_BOTTLES_EXCEPT = {1, 9}

# Games / film names in the artwork of M-series listings (disclaimer, third-party-name tag)
M_GAME = {
    39: ("film", "Star Wars", "Lucasfilm or The Walt Disney Company"),
    41: ("game", "Mario", "Nintendo"),
    43: ("game", "PlayStation", "Sony Interactive Entertainment"),
}

# Football club bar mats (32). title fragment -> (full club name, league, colours words, google colour, region,
# seo keyword (no club names), hook, close)
CLUBS = {
    "Arsenal": ("Arsenal Football Club", "the Premier League", "red and white", "Red", "North London",
                "Personalised Red & White Football Bar Mat",
                "Red panels, white blocks and a red and white ring at each end make it a proud spot for a North London fan’s pint.",
                "A smart gift for the Gooner who has everything, ready for the next derby."),
    "Aston Villa": ("Aston Villa Football Club", "the Premier League", "claret and sky blue", "Burgundy", "Birmingham",
                "Personalised Claret & Blue Football Bar Mat",
                "Deep claret with sky blue ends is a colour scheme Villa Park regulars will recognise straight away.",
                "Pair it with a pint glass for the Holte End regular in your life."),
    "Brentford": ("Brentford Football Club", "the Premier League", "red and white", "Red", "West London",
                "Personalised West London Football Bar Mat",
                "Red and white blocks give it a striped-shirt feel that Bees supporters will love.",
                "A great birthday present for a Brentford fan who has followed them through the leagues."),
    "Brighton and Hove Albion": ("Brighton & Hove Albion Football Club", "the Premier League", "blue and white", "Blue", "Sussex",
                "Personalised Blue & White Sussex Football Bar Mat",
                "Blue and white stripes running across the mat bring a bit of the south coast to the bar.",
                "Lovely for a Seagulls fan’s home bar, from the Amex to the kitchen."),
    "Burnley": ("Burnley Football Club", "the Premier League", "claret and sky blue", "Burgundy", "Lancashire",
                "Personalised Lancashire Claret Football Bar Mat",
                "Claret with bright sky blue ends gives it a Turf Moor feel for a Lancashire home bar.",
                "Wrap it up for the Clarets fan who never misses a home game."),
    "Chelsea": ("Chelsea Football Club", "the Premier League", "royal blue", "Blue", "London",
                "Personalised Royal Blue Football Bar Mat",
                "Royal blue from end to end, the colour that Stamford Bridge regulars wear with pride.",
                "A good gift for the Blues fan in your family, ready for match day."),
    "Crystal Palace": ("Crystal Palace Football Club", "the Premier League", "red and blue", "Blue", "South London",
                "Personalised Red & Blue South London Football Bar Mat",
                "Navy with red stripes gives it a Selhurst Park look for a South London home bar.",
                "Perfect for the Eagles fan who sings louder than anyone at the bar."),
    "Everton": ("Everton Football Club", "the Premier League", "royal blue and white", "Blue", "Merseyside",
                "Personalised Blue Merseyside Football Bar Mat",
                "Royal blue with lighter blue panels makes it a natural fit for a Toffees fan’s bar.",
                "A great present for an Evertonian, from the Gwladys Street to the home bar."),
    "Leeds": ("Leeds United Football Club", "the Premier League", "yellow, blue and white", "Yellow", "Yorkshire",
                "Personalised Yorkshire Football Bar Mat",
                "Yellow ends and a royal blue centre bring the Elland Road colours to a Yorkshire bar.",
                "Wrap it up for the Leeds fan who wants a bit of Elland Road in the kitchen."),
    "Leicester": ("Leicester City Football Club", "the Premier League", "royal blue and white", "Blue", "the East Midlands",
                "Personalised East Midlands Football Bar Mat",
                "Royal blue with crisp white panels gives it a proper Foxes look.",
                "A good gift for a Leicester fan who still talks about that title season."),
    "Liverpool": ("Liverpool Football Club", "the Premier League", "red", "Red", "Merseyside",
                "Personalised Red Merseyside Football Bar Mat",
                "Two shades of red make it the perfect bar mat for a Kop regular.",
                "Pick it up for a Reds fan’s birthday and their bar will be ready for every big European night."),
    "Man City": ("Manchester City Football Club", "the Premier League", "sky blue and white", "Light Blue", "Manchester",
                "Personalised Sky Blue Manchester Football Bar Mat",
                "Sky blue with white panels is the shade City fans know best.",
                "A great present for a Citizen with a trophy cabinet of a home bar."),
    "Man United": ("Manchester United Football Club", "the Premier League", "red and white", "Red", "Manchester",
                "Personalised Red Manchester Football Bar Mat",
                "Red with white blocks gives it the classic Old Trafford colours.",
                "A brilliant gift for the United fan who’s been there through thick and thin."),
    "Newcastle United": ("Newcastle United Football Club", "the Premier League", "black and white", "Black", "Tyneside",
                "Personalised Black & White Tyneside Football Bar Mat",
                "Black and white stripes from one end to the other, just like St James’ Park on match day.",
                "Wrap it for the Toon fan who never misses a match on the telly."),
    "Norwich City": ("Norwich City Football Club", "the Premier League", "yellow and green", "Yellow", "Norfolk",
                "Personalised Yellow & Green Norfolk Football Bar Mat",
                "Bright yellow with green ends gives it a proper Carrow Road feel.",
                "A cheerful present for the Canaries fan who’s on the ball."),
    "Southampton": ("Southampton Football Club", "the Premier League", "red and white", "Red", "Hampshire",
                "Personalised Red & White Hampshire Football Bar Mat",
                "Red and white stripes across the full length give it the look of a Saints shirt.",
                "Lovely for a Saints fan who wants a bit of St Mary’s at home."),
    "Tottenham": ("Tottenham Hotspur Football Club", "the Premier League", "white and navy", "White", "North London",
                "Personalised Navy & White North London Football Bar Mat",
                "Crisp white with navy ends gives it the clean look Spurs fans know.",
                "A great present for a Lilywhite with a home bar to show off."),
    "Watford": ("Watford Football Club", "the Premier League", "yellow, black and red", "Yellow", "Hertfordshire",
                "Personalised Yellow & Black Hertfordshire Football Bar Mat",
                "Bright yellow with black stripes brings the Vicarage Road colours to the bar.",
                "Wrap it up for the Hornets fan who never misses a home game."),
    "West Ham": ("West Ham United Football Club", "the Premier League", "claret and sky blue", "Burgundy", "East London",
                "Personalised Claret & Blue East London Football Bar Mat",
                "Claret with sky blue ends is the East London colour scheme Hammers fans grew up with.",
                "Perfect for the Irons fan who watches every match from their own bar stool."),
    "Wolves": ("Wolverhampton Wanderers Football Club", "the Premier League", "old gold and black", "Gold", "the Black Country",
                "Personalised Gold & Black Football Bar Mat",
                "Old gold with black ends gives it the Molineux look Wolves fans love.",
                "A great birthday present for a Wolves fan in the Black Country."),
    "Aberdeen": ("Aberdeen Football Club", "the Scottish Professional Football League", "red and white", "Red", "Aberdeen",
                "Personalised Red Aberdeen Football Bar Mat",
                "Bright red with white panels gives it the Pittodrie colours.",
                "A grand gift for a Dons fan in the north east."),
    "Celtic": ("Celtic Football Club", "the Scottish Professional Football League", "green and white", "Green", "Glasgow",
                "Personalised Green & White Hoops Football Bar Mat",
                "Green with white blocks gives it the look of the famous hoops.",
                "Perfect for a Bhoys fan who wants a bit of Paradise at home."),
    "Dundee": ("Dundee Football Club", "the Scottish Professional Football League", "navy and light blue", "Navy", "Dundee",
                "Personalised Navy & Blue Dundee Football Bar Mat",
                "Dark navy with light blue trim brings the Dens Park colours to the bar.",
                "A good gift for a Dark Blues fan with a home bar to show off."),
    "Dundee United": ("Dundee United Football Club", "the Scottish Professional Football League", "tangerine and black", "Orange", "Dundee",
                "Personalised Tangerine & Black Football Bar Mat",
                "Bright tangerine with black ends is impossible to miss, just like Tannadice on match day.",
                "Wrap it up for the Arabs fan in the family."),
    "Hearts": ("Heart of Midlothian Football Club", "the Scottish Professional Football League", "maroon and white", "Burgundy", "Edinburgh",
                "Personalised Maroon Edinburgh Football Bar Mat",
                "Deep maroon with white trim gives it the Tynecastle colours.",
                "A great present for a Jambo with their own home bar."),
    "Hibernian": ("Hibernian Football Club", "the Scottish Professional Football League", "green and white", "Green", "Edinburgh",
                "Personalised Green & White Edinburgh Football Bar Mat",
                "Green with white panels brings the Easter Road look to the bar.",
                "Perfect for a Hibees fan who wants a bit of Leith at home."),
    "Livingston": ("Livingston Football Club", "the Scottish Professional Football League", "black and gold", "Black", "West Lothian",
                "Personalised Black & Gold West Lothian Football Bar Mat",
                "Black with gold ends gives it the Livi colours for a home bar.",
                "A brilliant gift for a Lions fan in West Lothian."),
    "Motherwell": ("Motherwell Football Club", "the Scottish Professional Football League", "amber and claret", "Yellow", "Lanarkshire",
                "Personalised Amber & Claret Football Bar Mat",
                "Amber with a claret band gives it the Fir Park colours.",
                "A grand present for a Well fan in Lanarkshire."),
    "Rangers": ("Rangers Football Club", "the Scottish Professional Football League", "royal blue and white", "Blue", "Glasgow",
                "Personalised Royal Blue Glasgow Football Bar Mat",
                "Royal blue with white trim brings the Ibrox colours to the bar.",
                "Perfect for a Gers fan who wants their own bar to be part of the team."),
    "Ross County": ("Ross County Football Club", "the Scottish Professional Football League", "navy and red", "Navy", "the Highlands",
                "Personalised Navy & Red Highland Football Bar Mat",
                "Navy with red ends gives it the Victoria Park colours for a Highland home bar.",
                "A smart gift for a Staggies fan."),
    "St. Mirren": ("St Mirren Football Club", "the Scottish Professional Football League", "black and white", "Black", "Paisley",
                "Personalised Black & White Paisley Football Bar Mat",
                "Black and white stripes give it the classic Buddies look.",
                "A great present for a Saints fan in Paisley."),
    "St. Johnstone FC": ("St Johnstone Football Club", "the Scottish Professional Football League", "royal blue and white", "Blue", "Perth",
                "Personalised Blue & White Perth Football Bar Mat",
                "Royal blue with white and gold trim gives it the McDiarmid Park colours.",
                "Lovely for a Saints fan in Perth with a home bar."),
}

VE = {
    1: ("Union Jack red, white and blue", "Multicolor",
        "A red, white and blue Union Jack with a VE Day 80 roundel in the middle and 1945 and 2025 at either end.", True),
    2: ("gold Union Jack", "Gold",
        "A gold and white Union Jack with a VE Day 80 roundel in the centre and 1945 and 2025 at each end.", True),
    3: ("silver and grey Union Jack", "Grey",
        "A silver-grey Union Jack with a VE Day 80 roundel in the centre and the years 1945 and 2025.", True),
    4: ("gold lettering", "Gold",
        "Gold with a faded Union Jack behind bold white lettering: VE DAY, 80TH ANNIVERSARY, 8TH MAY 2025, VICTORY IN EUROPE and A SHARED MOMENT OF CELEBRATION.", False),
    5: ("red and gold Union Jack lettering", "Red",
        "A red, gold and navy Union Jack behind white lettering: VE DAY, 80TH ANNIVERSARY, 8TH MAY 2025, VICTORY IN EUROPE and A SHARED MOMENT OF CELEBRATION.", False),
}
