"""A6 star card packs (music and film Printed Signature cards), 8 Oct 2026.

Builds, for each pack in PACKS:
  - "<title> - PRINT.pdf": 6 pages, A6 landscape 148 x 105 mm + 3 mm bleed (154 x 111 mm), one card per page,
    the existing A4 300 dpi poster artwork scaled to cover the bleed (about 4% of the outer black border is
    trimmed), images at 300 dpi. No cut lines on the print file.
  - "<title> - CUT.svg": the trim template (layers Artwork = bleed box guide, CUT = red 0.25 mm trim path at
    148 x 105 mm), ASCII so it can go straight into Dropbox.
  - product images (2000 x 2000): 1 main grid (no text), 2 scattered on a light wall, 3 size guide.

Source artwork: the A4 landscape 4961 x 3508 px poster files already in the store / Dropbox
(see SRC). Nothing is generated by AI; no faces are sourced from the web.

Usage: python3 a6_star_card_packs.py SRC_DIR OUT_DIR
"""
import math
import os
import random
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageFont
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

PACKS = {
    "FOXY-PRESS-PDPSAPCP-01": {
        "title": "Pop Divas Printed Signature A6 Poster Card Pack",
        "cards": ["m_taylor", "m_adele", "m_ariana", "m_pink", "x_beyonce", "x_whitney"],
    },
    "FOXY-PRESS-RSPSAPCP-01": {
        "title": "Rap Stars Printed Signature A6 Poster Card Pack",
        "cards": ["r_drake", "r_eminem", "r_kendrick", "r_stormzy", "r_centralcee", "r_dave"],
    },
    "FOXY-PRESS-HIPSAPCP-01": {
        "title": "Hollywood Icons Printed Signature A6 Poster Card Pack",
        "cards": ["f_marilyn", "f_audrey", "f_grace", "f_elizabeth", "f_judy", "f_vivien"],
    },
    "FOXY-PRESS-LLPSAPCP-01": {
        "title": "Leading Ladies Printed Signature A6 Poster Card Pack",
        "cards": ["g_margot", "g_scarlett", "g_jennifer", "g_julia", "g_kate", "g_meryl"],
    },
}

TRIM_W, TRIM_H, BLEED = 148.0, 105.0, 3.0
PAGE_W, PAGE_H = TRIM_W + 2 * BLEED, TRIM_H + 2 * BLEED
DPI = 300
BG = (244, 241, 236)
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
FONT_REG = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"


def cover(im, w_px, h_px):
    """Scale to cover w x h, centre crop."""
    s = max(w_px / im.width, h_px / im.height)
    r = im.resize((math.ceil(im.width * s), math.ceil(im.height * s)), Image.LANCZOS)
    x, y = (r.width - w_px) // 2, (r.height - h_px) // 2
    return r.crop((x, y, x + w_px, y + h_px))


def print_pdf(cards, path):
    w_px, h_px = round(PAGE_W / 25.4 * DPI), round(PAGE_H / 25.4 * DPI)
    c = canvas.Canvas(path, pagesize=(PAGE_W * mm, PAGE_H * mm))
    c.setTitle(os.path.basename(path))
    c.setAuthor("Foxy Printing")
    tmp = []
    for i, im in enumerate(cards):
        page = cover(im, w_px, h_px).convert("RGB")
        jp = f"{path}.card{i + 1}.jpg"
        page.save(jp, quality=93, dpi=(DPI, DPI), subsampling=0)  # embedded as JPEG (DCT), keeps the PDF small
        tmp.append(jp)
        c.drawImage(jp, 0, 0, PAGE_W * mm, PAGE_H * mm)
        c.showPage()
    c.save()
    for jp in tmp:
        os.remove(jp)


def cut_svg(path, title):
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- {title}: A6 trim template, one card. Page = 154 x 111 mm (3 mm bleed). CUT = red 0.25 mm trim at 148 x 105 mm. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{PAGE_W}mm" height="{PAGE_H}mm" viewBox="0 0 {PAGE_W} {PAGE_H}">
  <g id="Artwork">
    <rect x="0" y="0" width="{PAGE_W}" height="{PAGE_H}" fill="none" stroke="#999999" stroke-width="0.1" stroke-dasharray="1,1"/>
    <rect x="{BLEED * 2}" y="{BLEED * 2}" width="{TRIM_W - 2 * BLEED}" height="{TRIM_H - 2 * BLEED}" fill="none" stroke="#00AEEF" stroke-width="0.1" stroke-dasharray="0.5,0.5"/>
  </g>
  <g id="CUT">
    <rect x="{BLEED}" y="{BLEED}" width="{TRIM_W}" height="{TRIM_H}" fill="none" stroke="#FF0000" stroke-width="0.25"/>
  </g>
</svg>
'''
    open(path, "w", encoding="ascii").write(svg)


def shadowed(card, radius=18, offset=(10, 14)):
    pad = radius * 3
    sh = Image.new("RGBA", (card.width + pad * 2, card.height + pad * 2), (0, 0, 0, 0))
    card = card.convert("RGBA")
    box = Image.new("RGBA", card.size, (0, 0, 0, 110))
    sh.paste(box, (pad + offset[0], pad + offset[1]), card.split()[3])  # shadow follows the card shape
    sh = sh.filter(ImageFilter.GaussianBlur(radius))
    sh.paste(card.convert("RGBA"), (pad, pad))
    return sh


def trim_card(im, w):
    """Card as it looks after trimming (A6 ratio 148:105)."""
    h = round(w * TRIM_H / TRIM_W)
    return cover(im, w, h)


def img_grid(cards, path):
    S = 2000
    out = Image.new("RGB", (S, S), BG)
    cw = 610
    ch = round(cw * TRIM_H / TRIM_W)
    gap_x, gap_y = 40, 60
    total_w = 3 * cw + 2 * gap_x
    total_h = 2 * ch + gap_y
    x0, y0 = (S - total_w) // 2, (S - total_h) // 2
    for i, im in enumerate(cards):
        card = shadowed(trim_card(im, cw))
        x = x0 + (i % 3) * (cw + gap_x)
        y = y0 + (i // 3) * (ch + gap_y)
        out.paste(card, (x - 54, y - 54), card)
    out.save(path, quality=90)


def img_scatter(cards, path, seed=7):
    rnd = random.Random(seed)
    S = 2000
    out = Image.new("RGB", (S, S), (232, 226, 216))
    cw = 820
    spots = [(140, 220), (1040, 170), (160, 760), (1060, 720), (300, 1300), (1000, 1290)]
    for (x, y), im in zip(spots, cards):
        card = trim_card(im, cw).convert("RGBA")
        card = card.rotate(rnd.uniform(-7, 7), resample=Image.BICUBIC, expand=True)
        card = shadowed(card, radius=14, offset=(8, 12))
        out.paste(card, (x - 42, y - 42), card)
    out.save(path, quality=90)


def img_size(cards, path):
    S = 2000
    out = Image.new("RGB", (S, S), BG)
    d = ImageDraw.Draw(out)
    cw = 1300
    ch = round(cw * TRIM_H / TRIM_W)
    x0, y0 = (S - cw) // 2, 430
    card = shadowed(trim_card(cards[0], cw))
    out.paste(card, (x0 - 54, y0 - 54), card)
    f = ImageFont.truetype(FONT, 64)
    fs = ImageFont.truetype(FONT_REG, 52)
    col = (40, 40, 40)
    # width arrow
    ya = y0 + ch + 90
    d.line([(x0, ya), (x0 + cw, ya)], fill=col, width=6)
    for xx, sgn in ((x0, 1), (x0 + cw, -1)):
        d.polygon([(xx, ya), (xx + 30 * sgn, ya - 18), (xx + 30 * sgn, ya + 18)], fill=col)
    t = "148 mm"
    tw = d.textlength(t, font=f)
    d.text(((S - tw) / 2, ya + 30), t, font=f, fill=col)
    # height arrow
    xa = x0 + cw + 90
    d.line([(xa, y0), (xa, y0 + ch)], fill=col, width=6)
    for yy, sgn in ((y0, 1), (y0 + ch, -1)):
        d.polygon([(xa, yy), (xa - 18, yy + 30 * sgn), (xa + 18, yy + 30 * sgn)], fill=col)
    txt = Image.new("RGBA", (400, 90), (0, 0, 0, 0))
    ImageDraw.Draw(txt).text((0, 0), "105 mm", font=f, fill=col)
    txt = txt.rotate(90, expand=True)
    out.paste(txt, (xa + 25, y0 + ch // 2 - 200), txt)
    for i, line in enumerate(["A6 cards  |  pack of 6", "350gsm premium card"]):
        tw = d.textlength(line, font=fs)
        d.text(((S - tw) / 2, 150 + i * 80), line, font=fs, fill=col)
    out.save(path, quality=90)


def main(src, out):
    os.makedirs(out, exist_ok=True)
    for sku, p in PACKS.items():
        cards = [Image.open(os.path.join(src, n + ".jpg")).convert("RGB") for n in p["cards"]]
        for im, n in zip(cards, p["cards"]):
            assert im.size == (4961, 3508), (n, im.size)
        base = os.path.join(out, sku)
        os.makedirs(base, exist_ok=True)
        print_pdf(cards, os.path.join(base, f"{p['title']} - {sku} - PRINT.pdf"))
        cut_svg(os.path.join(base, f"{p['title']} - CUT.svg"), p["title"])
        img_grid(cards, os.path.join(base, "1-main.jpg"))
        img_scatter(cards, os.path.join(base, "2-wall.jpg"))
        img_size(cards, os.path.join(base, "3-size.jpg"))
        print(sku, "ok")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
