#!/usr/bin/env python3
"""Writes theme/assets/leavers-photos.js from garment-photos/manifest.json (photos live in Shopify Files)."""
import json, os
here = os.path.dirname(os.path.abspath(__file__))
m = json.load(open(os.path.join(here, '../garment-photos/manifest.json')))
out = {}
for product, colours in m.items():
    out[product] = [{
        'id': c['id'], 'name': c['name'], 'hex': c['hex'], 'trim': c.get('trim', c['hex']),
        'front': c['files']['front'], 'back': c['files']['back'], 'real': c.get('real', True)
    } for c in colours]
js = ('/* Generated by tools/build-photo-manifest.py: real AWDis garment photos hosted in Shopify Files. */\n'
      'window.LEAVERS_PHOTOS = ' + json.dumps({'base': 'https://cdn.shopify.com/s/files/1/1774/9115/files/', 'products': out}, indent=1) + ';\n')
open(os.path.join(here, '../theme/assets/leavers-photos.js'), 'w').write(js)
print({k: len(v) for k, v in out.items()})
